const cidadesUF = {
  "Abaetetuba": "PA",
  "Abaiara": "CE",
  "Abaira": "BA",
  "Abare": "BA",
  "Abatia": "PR",
  "Abdon Batista": "SC",
  "Abel Figueiredo": "PA",
  "Abelardo Luz": "SC",
  "Abreu E Lima": "PE",
  "Abreulandia": "TO",
  "Acajutiba": "BA",
  "Acara": "PA",
  "Acarape": "CE",
  "Acarau": "CE",
  "Acari": "RN",
  "Acaua": "PI",
  "Acegua": "RS",
  "Acopiara": "CE",
  "Acorizal": "MT",
  "Acrelandia": "AC",
  "Acu": "RN",
  "Adamantina": "SP",
  "Adolfo": "SP",
  "Adrianopolis": "PR",
  "Adustina": "BA",
  "Afogados Da Ingazeira": "PE",
  "Afonso Bezerra": "RN",
  "Afonso Claudio": "ES",
  "Afranio": "PE",
  "Afua": "PA",
  "Agrestina": "PE",
  "Agricolandia": "PI",
  "Agrolandia": "SC",
  "Agronomica": "SC",
  "Agua Azul Do Norte": "PA",
  "Agua Boa": "MT",
  "Agua Branca": "PI",
  "Agua Doce": "SC",
  "Agua Doce Do Norte": "ES",
  "Agua Fria": "BA",
  "Agua Nova": "RN",
  "Agua Preta": "PE",
  "Agua Santa": "RS",
  "Aguai": "SP",
  "Aguas Belas": "PE",
  "Aguas Da Prata": "SP",
  "Aguas De Chapeco": "SC",
  "Aguas De Lindoia": "SP",
  "Aguas De Santa Barbara": "SP",
  "Aguas De Sao Pedro": "SP",
  "Aguas Frias": "SC",
  "Aguas Mornas": "SC",
  "Agudo": "RS",
  "Agudos": "SP",
  "Agudos Do Sul": "PR",
  "Aguia Branca": "ES",
  "Aguiar": "PB",
  "Aguiarnopolis": "TO",
  "Aiquara": "BA",
  "Aiuaba": "CE",
  "Ajuricaba": "RS",
  "Alagoa Grande": "PB",
  "Alagoa Nova": "PB",
  "Alagoinha": "PB",
  "Alagoinha Do Piaui": "PI",
  "Alagoinhas": "BA",
  "Alambari": "SP",
  "Alcantaras": "CE",
  "Alcantil": "PB",
  "Alcobaca": "BA",
  "Alecrim": "RS",
  "Alegre": "ES",
  "Alegrete": "RS",
  "Alegrete Do Piaui": "PI",
  "Alegria": "RS",
  "Alenquer": "PA",
  "Alexandria": "RN",
  "Alfredo Chaves": "ES",
  "Alfredo Marcondes": "SP",
  "Alfredo Wagner": "SC",
  "Algodao De Jandaira": "PB",
  "Alhandra": "PB",
  "Alianca": "PE",
  "Alianca Do Tocantins": "TO",
  "Almadina": "BA",
  "Almas": "TO",
  "Almeirim": "PA",
  "Almino Afonso": "RN",
  "Almirante Tamandare": "PR",
  "Almirante Tamandare Do Sul": "RS",
  "Alpestre": "RS",
  "Alta Floresta": "MT",
  "Altair": "SP",
  "Altamira": "PA",
  "Altamira Do Parana": "PR",
  "Altaneira": "CE",
  "Altinho": "PE",
  "Altinopolis": "SP",
  "Alto Alegre": "SP",
  "Alto Araguaia": "MT",
  "Alto Bela Vista": "SC",
  "Alto Boa Vista": "MT",
  "Alto Do Rodrigues": "RN",
  "Alto Feliz": "RS",
  "Alto Garcas": "MT",
  "Alto Longa": "PI",
  "Alto Paraguai": "MT",
  "Alto Parana": "PR",
  "Alto Paraíso": "PR",
  "Alto Piquiri": "PR",
  "Alto Rio Novo": "ES",
  "Alto Santo": "CE",
  "Alto Taquari": "MT",
  "Altonia": "PR",
  "Altos": "PI",
  "Aluminio": "SP",
  "Alvares Florence": "SP",
  "Alvares Machado": "SP",
  "Alvaro De Carvalho": "SP",
  "Alvinlandia": "SP",
  "Alvorada": "RS",
  "Alvorada Do Gurgueia": "PI",
  "Alvorada Do Sul": "PR",
  "Amajari": "RR",
  "Amapa": "AP",
  "Amapora": "PR",
  "Amaraji": "PE",
  "Amaral Ferrador": "RS",
  "Amarante": "PI",
  "Amargosa": "BA",
  "Amelia Rodrigues": "BA",
  "America Dourada": "BA",
  "Americana": "SP",
  "Americo Brasiliense": "SP",
  "Americo De Campos": "SP",
  "Ametista Do Sul": "RS",
  "Amontada": "CE",
  "Amparo": "SP",
  "Amparo De Sao Francisco": "SE",
  "Ampere": "PR",
  "Anadia": "AL",
  "Anage": "BA",
  "Anahy": "PR",
  "Anajas": "PA",
  "Analandia": "SP",
  "Ananas": "TO",
  "Ananindeua": "PA",
  "Anapu": "PA",
  "Anchieta": "ES",
  "Andarai": "BA",
  "Andira": "PR",
  "Andorinha": "BA",
  "Andradina": "SP",
  "Andre Da Rocha": "RS",
  "Angatuba": "SP",
  "Angelim": "PE",
  "Angelina": "SC",
  "Angical": "BA",
  "Angical Do Piaui": "PI",
  "Angico": "TO",
  "Angicos": "RN",
  "Angra Dos Reis": "RJ",
  "Anguera": "BA",
  "Angulo": "PR",
  "Anhembi": "SP",
  "Anhumas": "SP",
  "Anisio De Abreu": "PI",
  "Anita Garibaldi": "SC",
  "Anitapolis": "SC",
  "Anta Gorda": "RS",
  "Antas": "BA",
  "Antonina": "PR",
  "Antonina Do Norte": "CE",
  "Antonio Almeida": "PI",
  "Antonio Cardoso": "BA",
  "Antonio Carlos": "SC",
  "Antonio Goncalves": "BA",
  "Antonio Martins": "RN",
  "Antonio Olinto": "PR",
  "Antonio Prado": "RS",
  "Aparecida": "SP",
  "Aparecida Do Rio Negro": "TO",
  "Aperibe": "RJ",
  "Apiaca": "ES",
  "Apiacas": "MT",
  "Apiai": "SP",
  "Apiuna": "SC",
  "Apodi": "RN",
  "Apora": "BA",
  "Apuarema": "BA",
  "Apucarana": "PR",
  "Apuiares": "CE",
  "Aquidaba": "SE",
  "Aquiraz": "CE",
  "Arabuta": "SC",
  "Aracagi": "PB",
  "Aracaju": "SE",
  "Aracariguama": "SP",
  "Aracas": "BA",
  "Aracati": "CE",
  "Aracatu": "BA",
  "Aracatuba": "SP",
  "Araci": "BA",
  "Aracoiaba": "CE",
  "Aracoiaba Da Serra": "SP",
  "Aracruz": "ES",
  "Aragominas": "TO",
  "Araguacema": "TO",
  "Araguacu": "TO",
  "Araguaiana": "MT",
  "Araguaina": "TO",
  "Araguainha": "MT",
  "Araguana": "TO",
  "Araguatins": "TO",
  "Aramari": "BA",
  "Arambare": "RS",
  "Aramina": "SP",
  "Arandu": "SP",
  "Arapei": "SP",
  "Arapiraca": "AL",
  "Arapoema": "TO",
  "Arapongas": "PR",
  "Arapoti": "PR",
  "Arapua": "PR",
  "Araputanga": "MT",
  "Araquari": "SC",
  "Arara": "PB",
  "Ararangua": "SC",
  "Araraquara": "SP",
  "Araras": "SP",
  "Ararenda": "CE",
  "Ararica": "RS",
  "Araripe": "CE",
  "Araripina": "PE",
  "Araruama": "RJ",
  "Araruna": "PR",
  "Arataca": "BA",
  "Aratiba": "RS",
  "Aratuba": "CE",
  "Aratuipe": "BA",
  "Araua": "SE",
  "Araucaria": "PR",
  "Arco-Iris": "SP",
  "Arcoverde": "PE",
  "Areal": "RJ",
  "Arealva": "SP",
  "Areia": "PB",
  "Areia Branca": "RN",
  "Areia De Baraunas": "PB",
  "Areial": "PB",
  "Areias": "SP",
  "Areiopolis": "SP",
  "Arenapolis": "MT",
  "Ares": "RN",
  "Aripuana": "MT",
  "Ariranha": "SP",
  "Ariranha Do Ivai": "PR",
  "Armacao Dos Buzios": "RJ",
  "Armazem": "SC",
  "Arneiroz": "CE",
  "Aroazes": "PI",
  "Aroeiras": "PB",
  "Arraial": "PI",
  "Arraial Do Cabo": "RJ",
  "Arraias": "TO",
  "Arroio Do Meio": "RS",
  "Arroio Do Padre": "RS",
  "Arroio Do Sal": "RS",
  "Arroio Do Tigre": "RS",
  "Arroio Dos Ratos": "RS",
  "Arroio Grande": "RS",
  "Arroio Trinta": "SC",
  "Artur Nogueira": "SP",
  "Aruja": "SP",
  "Arvoredo": "SC",
  "Arvorezinha": "RS",
  "Ascurra": "SC",
  "Aspasia": "SP",
  "Assai": "PR",
  "Assare": "CE",
  "Assis": "SP",
  "Assis Brasil": "AC",
  "Assis Chateaubriand": "PR",
  "Assuncao": "PB",
  "Assuncao Do Piaui": "PI",
  "Astorga": "PR",
  "Atalaia": "AL",
  "Atalanta": "SC",
  "Atibaia": "SP",
  "Atilio Vivacqua": "ES",
  "Augustinopolis": "TO",
  "Augusto Correa": "PA",
  "Augusto Pestana": "RS",
  "Augusto Severo": "RN",
  "Aurea": "RS",
  "Aurelino Leal": "BA",
  "Auriflama": "SP",
  "Aurora": "SC",
  "Aurora Do Para": "PA",
  "Aurora Do Tocantins": "TO",
  "Avai": "SP",
  "Avanhandava": "SP",
  "Avare": "SP",
  "Aveiro": "PA",
  "Avelino Lopes": "PI",
  "Axixa Do Tocantins": "TO",
  "Babaculandia": "TO",
  "Bady Bassitt": "SP",
  "Bage": "RS",
  "Bagre": "PA",
  "Baia Da Traicao": "PB",
  "Baia Formosa": "RN",
  "Baianopolis": "BA",
  "Baiao": "PA",
  "Baixa Grande": "BA",
  "Baixa Grande Do Ribeiro": "PI",
  "Baixio": "CE",
  "Baixo Guandu": "ES",
  "Balbinos": "SP",
  "Balneario Arroio Do Silva": "SC",
  "Balneario Barra Do Sul": "SC",
  "Balneario Camboriu": "SC",
  "Balneario Gaivota": "SC",
  "Balneario Pinhal": "RS",
  "Balsa Nova": "PR",
  "Balsas": "MA",
  "Balsamo": "SP",
  "Banabuiu": "CE",
  "Bananal": "SP",
  "Bananeiras": "PB",
  "Bandeirante": "SC",
  "Bandeirantes": "PR",
  "Bandeirantes Do Tocantins": "TO",
  "Bannach": "PA",
  "Banzae": "BA",
  "Barao": "RS",
  "Barao De Antonina": "SP",
  "Barao De Cotegipe": "RS",
  "Barao De Melgaco": "MT",
  "Barao Do Triunfo": "RS",
  "Barauna": "PB",
  "Barbalha": "CE",
  "Barbosa": "SP",
  "Barbosa Ferraz": "PR",
  "Barcarena": "PA",
  "Barcelona": "RN",
  "Bariri": "SP",
  "Barra": "BA",
  "Barra Bonita": "SC",
  "Barra Da Estiva": "BA",
  "Barra De Guabiraba": "PE",
  "Barra De Santa Rosa": "PB",
  "Barra De Santana": "PB",
  "Barra De Santo Antonio": "AL",
  "Barra De Sao Francisco": "ES",
  "Barra De Sao Miguel": "AL",
  "Barra Do Bugres": "MT",
  "Barra Do Chapeu": "SP",
  "Barra Do Choca": "BA",
  "Barra Do Garcas": "MT",
  "Barra Do Guarita": "RS",
  "Barra Do Jacare": "PR",
  "Barra Do Mendes": "BA",
  "Barra Do Ouro": "TO",
  "Barra Do Pirai": "RJ",
  "Barra Do Quarai": "RS",
  "Barra Do Ribeiro": "RS",
  "Barra Do Rio Azul": "RS",
  "Barra Do Rocha": "BA",
  "Barra Do Turvo": "SP",
  "Barra Dos Coqueiros": "SE",
  "Barra Funda": "RS",
  "Barra Mansa": "RJ",
  "Barra Velha": "SC",
  "Barracao": "PR",
  "Barras": "PI",
  "Barreira": "CE",
  "Barreiras": "BA",
  "Barreiras Do Piaui": "PI",
  "Barreiros": "PE",
  "Barretos": "SP",
  "Barrinha": "SP",
  "Barro": "CE",
  "Barro Alto": "BA",
  "Barro Duro": "PI",
  "Barro Preto": "BA",
  "Barrocas": "BA",
  "Barrolandia": "TO",
  "Barroquinha": "CE",
  "Barros Cassal": "RS",
  "Barueri": "SP",
  "Bastos": "SP",
  "Batalha": "PI",
  "Batatais": "SP",
  "Baturite": "CE",
  "Bauru": "SP",
  "Bayeux": "PB",
  "Bebedouro": "SP",
  "Beberibe": "CE",
  "Bela Cruz": "CE",
  "Bela Vista Da Caroba": "PR",
  "Bela Vista Do Paraiso": "PR",
  "Bela Vista Do Piaui": "PI",
  "Bela Vista Do Toldo": "SC",
  "Belem": "PA",
  "Belem De Maria": "PE",
  "Belem De Sao Francisco": "PE",
  "Belem Do Brejo Do Cruz": "PB",
  "Belem Do Piaui": "PI",
  "Belford Roxo": "RJ",
  "Belmonte": "BA",
  "Belo Campo": "BA",
  "Belo Jardim": "PE",
  "Belo Monte": "AL",
  "Belterra": "PA",
  "Beneditinos": "PI",
  "Benedito Novo": "SC",
  "Benevides": "PA",
  "Benjamin Constant Do Sul": "RS",
  "Bento De Abreu": "SP",
  "Bento Fernandes": "RN",
  "Bento Goncalves": "RS",
  "Bernardino Batista": "PB",
  "Bernardino De Campos": "SP",
  "Bernardo Sayao": "TO",
  "Bertioga": "SP",
  "Bertolinia": "PI",
  "Betania": "PE",
  "Betania Do Piaui": "PI",
  "Bezerros": "PE",
  "Biguacu": "SC",
  "Bilac": "SP",
  "Birigui": "SP",
  "Biritiba-Mirim": "SP",
  "Biritinga": "BA",
  "Bituruna": "PR",
  "Blumenau": "SC",
  "Boa Esperanca": "PR",
  "Boa Esperanca Do Iguacu": "PR",
  "Boa Esperanca Do Sul": "SP",
  "Boa Hora": "PI",
  "Boa Nova": "BA",
  "Boa Ventura": "PB",
  "Boa Ventura De Sao Roque": "PR",
  "Boa Viagem": "CE",
  "Boa Vista": "PB",
  "Boa Vista Da Aparecida": "PR",
  "Boa Vista Das Missoes": "RS",
  "Boa Vista Do Burica": "RS",
  "Boa Vista Do Cadeado": "RS",
  "Boa Vista Do Incra": "RS",
  "Boa Vista Do Sul": "RS",
  "Boa Vista Do Tupim": "BA",
  "Boca Da Mata": "AL",
  "Bocaina": "SP",
  "Bocaina Do Sul": "SC",
  "Bocaiuva Do Sul": "PR",
  "Bodo": "RN",
  "Bodoco": "PE",
  "Bofete": "SP",
  "Boituva": "SP",
  "Bom Conselho": "PE",
  "Bom Jardim": "RJ",
  "Bom Jardim Da Serra": "SC",
  "Bom Jesus": "PB",
  "Bom Jesus Da Lapa": "BA",
  "Bom Jesus Da Serra": "BA",
  "Bom Jesus Do Araguaia": "MT",
  "Bom Jesus Do Itabapoana": "RJ",
  "Bom Jesus Do Norte": "ES",
  "Bom Jesus Do Oeste": "SC",
  "Bom Jesus Do Sul": "PR",
  "Bom Jesus Do Tocantins": "PA",
  "Bom Jesus Dos Perdoes": "SP",
  "Bom Principio": "RS",
  "Bom Principio Do Piaui": "PI",
  "Bom Progresso": "RS",
  "Bom Retiro": "SC",
  "Bom Retiro Do Sul": "RS",
  "Bom Sucesso": "PB",
  "Bom Sucesso De Itarare": "SP",
  "Bom Sucesso Do Sul": "PR",
  "Bombinhas": "SC",
  "Bonfim": "RR",
  "Bonfim Do Piaui": "PI",
  "Boninal": "BA",
  "Bonito": "PA",
  "Bonito De Santa Fe": "PB",
  "Boqueirao": "PB",
  "Boqueirao Do Leao": "RS",
  "Boqueirao Do Piaui": "PI",
  "Boquim": "SE",
  "Boquira": "BA",
  "Bora": "SP",
  "Boraceia": "SP",
  "Borborema": "PB",
  "Borebi": "SP",
  "Borrazopolis": "PR",
  "Bossoroca": "RS",
  "Botucatu": "SP",
  "Botupora": "BA",
  "Botuvera": "SC",
  "Bozano": "RS",
  "Braco Do Norte": "SC",
  "Braco Do Trombudo": "SC",
  "Braga": "RS",
  "Braganca": "PA",
  "Braganca Paulista": "SP",
  "Braganey": "PR",
  "Branquinha": "AL",
  "Brasil Novo": "PA",
  "Brasilandia Do Sul": "PR",
  "Brasilandia Do Tocantins": "TO",
  "Brasileia": "AC",
  "Brasileira": "PI",
  "Brasilia": "DF",
  "Brasnorte": "MT",
  "Brauna": "SP",
  "Brejao": "PE",
  "Brejetuba": "ES",
  "Brejinho": "PE",
  "Brejinho De Nazare": "TO",
  "Brejo Alegre": "SP",
  "Brejo Da Madre De Deus": "PE",
  "Brejo Do Cruz": "PB",
  "Brejo Do Piaui": "PI",
  "Brejo Dos Santos": "PB",
  "Brejo Grande": "SE",
  "Brejo Grande Do Araguaia": "PA",
  "Brejo Santo": "CE",
  "Brejoes": "BA",
  "Brejolandia": "BA",
  "Breu Branco": "PA",
  "Breves": "PA",
  "Brochier": "RS",
  "Brodowski": "SP",
  "Brotas": "SP",
  "Brotas De Macaubas": "BA",
  "Brumado": "BA",
  "Brunopolis": "SC",
  "Brusque": "SC",
  "Buenos Aires": "PE",
  "Buerarema": "BA",
  "Buique": "PE",
  "Bujari": "AC",
  "Bujaru": "PA",
  "Buri": "SP",
  "Buritama": "SP",
  "Buriti Do Tocantins": "TO",
  "Buriti Dos Lopes": "PI",
  "Buriti Dos Montes": "PI",
  "Buritirama": "BA",
  "Buritizal": "SP",
  "Butia": "RS",
  "Caapora": "PB",
  "Caatiba": "BA",
  "Cabaceiras": "PB",
  "Cabaceiras Do Paraguacu": "BA",
  "Cabeceiras Do Piaui": "PI",
  "Cabedelo": "PB",
  "Cabo De Santo Agostinho": "PE",
  "Cabo Frio": "RJ",
  "Cabralia Paulista": "SP",
  "Cabreuva": "SP",
  "Cabrobo": "PE",
  "Cacador": "SC",
  "Cacapava": "SP",
  "Cacapava Do Sul": "RS",
  "Cacequi": "RS",
  "Caceres": "MT",
  "Cachoeira": "BA",
  "Cachoeira Do Arari": "PA",
  "Cachoeira Do Piria": "PA",
  "Cachoeira Do Sul": "RS",
  "Cachoeira Dos Indios": "PB",
  "Cachoeira Paulista": "SP",
  "Cachoeiras De Macacu": "RJ",
  "Cachoeirinha": "RS",
  "Cachoeiro De Itapemirim": "ES",
  "Cacimba De Areia": "PB",
  "Cacimba De Dentro": "PB",
  "Cacimbas": "PB",
  "Cacimbinhas": "AL",
  "Cacique Doble": "RS",
  "Caconde": "SP",
  "Cacule": "BA",
  "Caem": "BA",
  "Caetanos": "BA",
  "Caetes": "PE",
  "Caetite": "BA",
  "Cafarnaum": "BA",
  "Cafeara": "PR",
  "Cafelandia": "SP",
  "Cafezal Do Sul": "PR",
  "Caiabu": "SP",
  "Caibate": "RS",
  "Caibi": "SC",
  "Caicara": "RS",
  "Caicara Do Norte": "RN",
  "Caicara Do Rio Do Vento": "RN",
  "Caico": "RN",
  "Caieiras": "SP",
  "Cairu": "BA",
  "Caiua": "SP",
  "Cajamar": "SP",
  "Cajati": "SP",
  "Cajazeiras": "PB",
  "Cajazeiras Do Piaui": "PI",
  "Cajazeirinhas": "PB",
  "Cajobi": "SP",
  "Cajueiro": "AL",
  "Cajueiro Da Praia": "PI",
  "Cajuru": "SP",
  "Calcado": "PE",
  "Calcoene": "AP",
  "Caldas Brandao": "PB",
  "Caldeirao Grande": "BA",
  "Caldeirao Grande Do Piaui": "PI",
  "California": "PR",
  "Calmon": "SC",
  "Calumbi": "PE",
  "Camacan": "BA",
  "Camacari": "BA",
  "Camalau": "PB",
  "Camamu": "BA",
  "Camaqua": "RS",
  "Camaragibe": "PE",
  "Camargo": "RS",
  "Cambara": "PR",
  "Cambara Do Sul": "RS",
  "Cambe": "PR",
  "Cambira": "PR",
  "Camboriu": "SC",
  "Cambuci": "RJ",
  "Cameta": "PA",
  "Camocim": "CE",
  "Camocim De Sao Felix": "PE",
  "Campestre": "AL",
  "Campestre Da Serra": "RS",
  "Campina Da Lagoa": "PR",
  "Campina Das Missoes": "RS",
  "Campina Do Monte Alegre": "SP",
  "Campina Do Simao": "PR",
  "Campina Grande": "PB",
  "Campina Grande Do Sul": "PR",
  "Campinapolis": "MT",
  "Campinas": "SP",
  "Campinas Do Piaui": "PI",
  "Campinas Do Sul": "RS",
  "Campo Alegre": "AL",
  "Campo Alegre De Lourdes": "BA",
  "Campo Alegre Do Fidalgo": "PI",
  "Campo Belo Do Sul": "SC",
  "Campo Bom": "RS",
  "Campo Bonito": "PR",
  "Campo De Santana": "PB",
  "Campo Do Brito": "SE",
  "Campo Do Tenente": "PR",
  "Campo Ere": "SC",
  "Campo Formoso": "BA",
  "Campo Grande": "AL",
  "Campo Grande Do Piaui": "PI",
  "Campo Largo": "PR",
  "Campo Largo Do Piaui": "PI",
  "Campo Limpo Paulista": "SP",
  "Campo Magro": "PR",
  "Campo Maior": "PI",
  "Campo Mourao": "PR",
  "Campo Novo": "RS",
  "Campo Novo Do Parecis": "MT",
  "Campo Redondo": "RN",
  "Campo Verde": "MT",
  "Campos Borges": "RS",
  "Campos De Julio": "MT",
  "Campos Do Jordao": "SP",
  "Campos Dos Goytacazes": "RJ",
  "Campos Lindos": "TO",
  "Campos Novos": "SC",
  "Campos Novos Paulista": "SP",
  "Campos Sales": "CE",
  "Camutanga": "PE",
  "Canaa Dos Carajas": "PA",
  "Canabrava Do Norte": "MT",
  "Cananeia": "SP",
  "Canapi": "AL",
  "Canapolis": "BA",
  "Canarana": "MT",
  "Canas": "SP",
  "Canavieira": "PI",
  "Canavieiras": "BA",
  "Candeal": "BA",
  "Candeias": "BA",
  "Candelaria": "RS",
  "Candiba": "BA",
  "Candido De Abreu": "PR",
  "Candido Godoi": "RS",
  "Candido Mota": "SP",
  "Candido Rodrigues": "SP",
  "Candido Sales": "BA",
  "Candiota": "RS",
  "Candoi": "PR",
  "Canela": "RS",
  "Canelinha": "SC",
  "Canguaretama": "RN",
  "Cangucu": "RS",
  "Canhoba": "SE",
  "Canhotinho": "PE",
  "Caninde": "CE",
  "Caninde De Sao Francisco": "SE",
  "Canitar": "SP",
  "Canoas": "RS",
  "Canoinhas": "SC",
  "Cansancao": "BA",
  "Canta": "RR",
  "Cantagalo": "PR",
  "Canto Do Buriti": "PI",
  "Canudos": "BA",
  "Canudos Do Vale": "RS",
  "Capanema": "PA",
  "Capao Alto": "SC",
  "Capao Bonito": "SP",
  "Capao Da Canoa": "RS",
  "Capao Do Leao": "RS",
  "Capela": "SE",
  "Capela De Santana": "RS",
  "Capela Do Alto": "SP",
  "Capela Do Alto Alegre": "BA",
  "Capim": "PB",
  "Capim Grosso": "BA",
  "Capinzal": "SC",
  "Capistrano": "CE",
  "Capitao": "RS",
  "Capitao De Campos": "PI",
  "Capitao Gervasio Oliveira": "PI",
  "Capitao Leonidas Marques": "PR",
  "Capitao Poco": "PA",
  "Capivari": "SP",
  "Capivari De Baixo": "SC",
  "Capivari Do Sul": "RS",
  "Capixaba": "AC",
  "Capoeiras": "PE",
  "Capão Bonito Do Sul": "RS",
  "Capão Do Cipó": "RS",
  "Caraa": "RS",
  "Caracarai": "RR",
  "Caracol": "PI",
  "Caraguatatuba": "SP",
  "Caraibas": "BA",
  "Carambei": "PR",
  "Carapebus": "RJ",
  "Carapicuiba": "SP",
  "Caraubas": "PB",
  "Caraubas Do Piaui": "PI",
  "Caravelas": "BA",
  "Carazinho": "RS",
  "Cardeal Da Silva": "BA",
  "Cardoso": "SP",
  "Cardoso Moreira": "RJ",
  "Cariacica": "ES",
  "Caridade": "CE",
  "Caridade Do Piaui": "PI",
  "Carinhanha": "BA",
  "Carira": "SE",
  "Carire": "CE",
  "Cariri Do Tocantins": "TO",
  "Caririacu": "CE",
  "Carius": "CE",
  "Carlinda": "MT",
  "Carlopolis": "PR",
  "Carlos Barbosa": "RS",
  "Carlos Gomes": "RS",
  "Carmo": "RJ",
  "Carmolandia": "TO",
  "Carmopolis": "SE",
  "Carnaiba": "PE",
  "Carnauba Dos Dantas": "RN",
  "Carnaubais": "RN",
  "Carnaubal": "CE",
  "Carnaubeira Da Penha": "PE",
  "Carneiros": "AL",
  "Caroebe": "RR",
  "Carpina": "PE",
  "Carrapateira": "PB",
  "Carrasco Bonito": "TO",
  "Caruaru": "PE",
  "Casa Branca": "SP",
  "Casa Nova": "BA",
  "Casca": "RS",
  "Cascavel": "PR",
  "Caseara": "TO",
  "Caseiros": "RS",
  "Casimiro De Abreu": "RJ",
  "Casinhas": "PE",
  "Casserengue": "PB",
  "Cassia Dos Coqueiros": "SP",
  "Castanhal": "PA",
  "Castanheira": "MT",
  "Castelo": "ES",
  "Castelo Do Piaui": "PI",
  "Castilho": "SP",
  "Castro": "PR",
  "Castro Alves": "BA",
  "Catanduva": "SP",
  "Catanduvas": "PR",
  "Catarina": "CE",
  "Catende": "PE",
  "Catigua": "SP",
  "Catingueira": "PB",
  "Catolandia": "BA",
  "Catole Do Rocha": "PB",
  "Catu": "BA",
  "Catuipe": "RS",
  "Catunda": "CE",
  "Caturama": "BA",
  "Caturite": "PB",
  "Caucaia": "CE",
  "Caxambu Do Sul": "SC",
  "Caxias Do Sul": "RS",
  "Caxingo": "PI",
  "Ceara-Mirim": "RN",
  "Cedral": "SP",
  "Cedro": "CE",
  "Cedro De Sao Joao": "SE",
  "Celso Ramos": "SC",
  "Centenario": "TO",
  "Centenario Do Sul": "PR",
  "Central": "BA",
  "Cerqueira Cesar": "SP",
  "Cerquilho": "SP",
  "Cerrito": "RS",
  "Cerro Azul": "PR",
  "Cerro Branco": "RS",
  "Cerro Cora": "RN",
  "Cerro Grande": "RS",
  "Cerro Grande Do Sul": "RS",
  "Cerro Largo": "RS",
  "Cerro Negro": "SC",
  "Cesario Lange": "SP",
  "Ceu Azul": "PR",
  "Cha De Alegria": "PE",
  "Cha Grande": "PE",
  "Cha Preta": "AL",
  "Chapada": "RS",
  "Chapada Da Natividade": "TO",
  "Chapada De Areia": "TO",
  "Chapada Dos Guimaraes": "MT",
  "Chapadao Do Lageado": "SC",
  "Chapeco": "SC",
  "Charqueada": "SP",
  "Charqueadas": "RS",
  "Charrua": "RS",
  "Chaval": "CE",
  "Chavantes": "SP",
  "Chaves": "PA",
  "Chiapetta": "RS",
  "Chopinzinho": "PR",
  "Choro": "CE",
  "Chorozinho": "CE",
  "Chorrocho": "BA",
  "Chui": "RS",
  "Chuvisca": "RS",
  "Cianorte": "PR",
  "Cicero Dantas": "BA",
  "Cidade Gaucha": "PR",
  "Cidreira": "RS",
  "Cipo": "BA",
  "Ciriaco": "RS",
  "Claudia": "MT",
  "Clementina": "SP",
  "Clevelandia": "PR",
  "Coaraci": "BA",
  "Cocal": "PI",
  "Cocal De Telha": "PI",
  "Cocal Do Sul": "SC",
  "Cocal Dos Alves": "PI",
  "Cocalinho": "MT",
  "Cocos": "BA",
  "Coite Do Noia": "AL",
  "Coivaras": "PI",
  "Colares": "PA",
  "Colatina": "ES",
  "Colider": "MT",
  "Colina": "SP",
  "Colinas": "RS",
  "Colinas Do Tocantins": "TO",
  "Colmeia": "TO",
  "Colniza": "MT",
  "Colombia": "SP",
  "Colombo": "PR",
  "Colonia Do Gurgueia": "PI",
  "Colonia Do Piaui": "PI",
  "Colonia Leopoldina": "AL",
  "Colorado": "RS",
  "Combinado": "TO",
  "Comendador Levy Gasparian": "RJ",
  "Comodoro": "MT",
  "Conceicao": "PB",
  "Conceicao Da Barra": "ES",
  "Conceicao Da Feira": "BA",
  "Conceicao De Macabu": "RJ",
  "Conceicao Do Almeida": "BA",
  "Conceicao Do Araguaia": "PA",
  "Conceicao Do Caninde": "PI",
  "Conceicao Do Castelo": "ES",
  "Conceicao Do Coite": "BA",
  "Conceicao Do Jacuipe": "BA",
  "Conceicao Do Tocantins": "TO",
  "Conchal": "SP",
  "Conchas": "SP",
  "Concordia": "SC",
  "Concordia Do Para": "PA",
  "Condado": "PB",
  "Conde": "BA",
  "Condeuba": "BA",
  "Condor": "RS",
  "Confresa": "MT",
  "Congo": "PB",
  "Congonhinhas": "PR",
  "Conselheiro Mairinck": "PR",
  "Constantina": "RS",
  "Contenda": "PR",
  "Contendas Do Sincora": "BA",
  "Coqueiro Baixo": "RS",
  "Coqueiro Seco": "AL",
  "Coqueiros Do Sul": "RS",
  "Coracao De Maria": "BA",
  "Corbelia": "PR",
  "Cordeiro": "RJ",
  "Cordeiropolis": "SP",
  "Cordeiros": "BA",
  "Cordilheira Alta": "SC",
  "Coreau": "CE",
  "Coremas": "PB",
  "Coribe": "BA",
  "Cornelio Procopio": "PR",
  "Coroados": "SP",
  "Coronel Barros": "RS",
  "Coronel Bicaco": "RS",
  "Coronel Domingos Soares": "PR",
  "Coronel Ezequiel": "RN",
  "Coronel Freitas": "SC",
  "Coronel Joao Pessoa": "RN",
  "Coronel Joao Sa": "BA",
  "Coronel Jose Dias": "PI",
  "Coronel Macedo": "SP",
  "Coronel Martins": "SC",
  "Coronel Pilar": "RS",
  "Coronel Vivida": "PR",
  "Correia Pinto": "SC",
  "Corrente": "PI",
  "Correntes": "PE",
  "Correntina": "BA",
  "Cortes": "PE",
  "Corumbatai": "SP",
  "Corumbatai Do Sul": "PR",
  "Corupa": "SC",
  "Coruripe": "AL",
  "Cosmopolis": "SP",
  "Cosmorama": "SP",
  "Cotegipe": "BA",
  "Cotia": "SP",
  "Cotipora": "RS",
  "Cotriguacu": "MT",
  "Couto De Magalhaes": "TO",
  "Coxilha": "RS",
  "Coxixola": "PB",
  "Craibas": "AL",
  "Crateus": "CE",
  "Crato": "CE",
  "Cravinhos": "SP",
  "Cravolandia": "BA",
  "Criciuma": "SC",
  "Crisopolis": "BA",
  "Crissiumal": "RS",
  "Cristais Paulista": "SP",
  "Cristal": "RS",
  "Cristal Do Sul": "RS",
  "Cristalandia": "TO",
  "Cristalandia Do Piaui": "PI",
  "Cristinapolis": "SE",
  "Cristino Castro": "PI",
  "Cristopolis": "BA",
  "Crixas Do Tocantins": "TO",
  "Croata": "CE",
  "Cruz": "CE",
  "Cruz Alta": "RS",
  "Cruz Das Almas": "BA",
  "Cruz Do Espirito Santo": "PB",
  "Cruz Machado": "PR",
  "Cruzalia": "SP",
  "Cruzaltense": "RS",
  "Cruzeiro": "SP",
  "Cruzeiro Do Iguacu": "PR",
  "Cruzeiro Do Oeste": "PR",
  "Cruzeiro Do Sul": "AC",
  "Cruzeta": "RN",
  "Cruzmaltina": "PR",
  "Cubatao": "SP",
  "Cubati": "PB",
  "Cuiaba": "MT",
  "Cuite": "PB",
  "Cuite De Mamanguape": "PB",
  "Cuitegi": "PB",
  "Cumaru": "PE",
  "Cumaru Do Norte": "PA",
  "Cumbe": "SE",
  "Cunha": "SP",
  "Cunha Pora": "SC",
  "Cunhatai": "SC",
  "Cupira": "PE",
  "Curaca": "BA",
  "Curimata": "PI",
  "Curionopolis": "PA",
  "Curitiba": "PR",
  "Curitibanos": "SC",
  "Curiuva": "PR",
  "Currais": "PI",
  "Currais Novos": "RN",
  "Curral De Cima": "PB",
  "Curral Novo Do Piaui": "PI",
  "Curral Velho": "PB",
  "Curralinho": "PA",
  "Curralinhos": "PI",
  "Curua": "PA",
  "Curuca": "PA",
  "Curvelandia": "MT",
  "Custodia": "PE",
  "Cutias": "AP",
  "Damiao": "PB",
  "Darcinopolis": "TO",
  "Dario Meira": "BA",
  "David Canabarro": "RS",
  "Delmiro Gouveia": "AL",
  "Demerval Lobao": "PI",
  "Denise": "MT",
  "Deputado Irapuan Pinheiro": "CE",
  "Derrubadas": "RS",
  "Descalvado": "SP",
  "Descanso": "SC",
  "Desterro": "PB",
  "Dezesseis De Novembro": "RS",
  "Diadema": "SP",
  "Diamante": "PB",
  "Diamante Do Norte": "PR",
  "Diamante Do Sul": "PR",
  "Diamantino": "MT",
  "Dianopolis": "TO",
  "Dilermando De Aguiar": "RS",
  "Dionisio Cerqueira": "SC",
  "Dirce Reis": "SP",
  "Dirceu Arcoverde": "PI",
  "Divina Pastora": "SE",
  "Divino De Sao Lourenco": "ES",
  "Divinolandia": "SP",
  "Divinopolis Do Tocantins": "TO",
  "Dobrada": "SP",
  "Dois Corregos": "SP",
  "Dois Irmaos": "RS",
  "Dois Irmaos Das Missoes": "RS",
  "Dois Irmaos Do Tocantins": "TO",
  "Dois Lajeados": "RS",
  "Dois Riachos": "AL",
  "Dois Vizinhos": "PR",
  "Dolcinopolis": "SP",
  "Dom Aquino": "MT",
  "Dom Basilio": "BA",
  "Dom Eliseu": "PA",
  "Dom Expedito Lopes": "PI",
  "Dom Feliciano": "RS",
  "Dom Inocencio": "PI",
  "Dom Macedo Costa": "BA",
  "Dom Pedrito": "RS",
  "Dom Pedro De Alcantara": "RS",
  "Domingos Martins": "ES",
  "Domingos Mourao": "PI",
  "Dona Emma": "SC",
  "Dona Francisca": "RS",
  "Dona Ines": "PB",
  "Dores Do Rio Preto": "ES",
  "Dormentes": "PE",
  "Douradina": "PR",
  "Dourado": "SP",
  "Doutor Camargo": "PR",
  "Doutor Mauricio Cardoso": "RS",
  "Doutor Pedrinho": "SC",
  "Doutor Ricardo": "RS",
  "Doutor Severiano": "RN",
  "Doutor Ulysses": "PR",
  "Dracena": "SP",
  "Duartina": "SP",
  "Duas Barras": "RJ",
  "Duas Estradas": "PB",
  "Duere": "TO",
  "Dumont": "SP",
  "Duque De Caxias": "RJ",
  "Echapora": "SP",
  "Ecoporanga": "ES",
  "Eldorado": "SP",
  "Eldorado Do Sul": "RS",
  "Eldorado Dos Carajas": "PA",
  "Elesbao Veloso": "PI",
  "Elias Fausto": "SP",
  "Eliseu Martins": "PI",
  "Elisiario": "SP",
  "Elisio Medrado": "BA",
  "Emas": "PB",
  "Embauba": "SP",
  "Embu": "SP",
  "Embu-Guacu": "SP",
  "Emilianopolis": "SP",
  "Encantado": "RS",
  "Encanto": "RN",
  "Encruzilhada": "BA",
  "Encruzilhada Do Sul": "RS",
  "Eneas Marques": "PR",
  "Engenheiro Beltrao": "PR",
  "Engenheiro Coelho": "SP",
  "Engenheiro Paulo De Frontin": "RJ",
  "Engenho Velho": "RS",
  "Entre Rios": "BA",
  "Entre Rios Do Oeste": "PR",
  "Entre Rios Do Sul": "RS",
  "Entre-Ijuis": "RS",
  "Epitaciolandia": "AC",
  "Equador": "RN",
  "Erebango": "RS",
  "Erechim": "RS",
  "Erere": "CE",
  "Erico Cardoso": "BA",
  "Ermo": "SC",
  "Ernestina": "RS",
  "Erval Grande": "RS",
  "Erval Seco": "RS",
  "Erval Velho": "SC",
  "Escada": "PE",
  "Esmeralda": "RS",
  "Esperanca": "PB",
  "Esperanca Do Sul": "RS",
  "Esperanca Nova": "PR",
  "Esperantina": "PI",
  "Espigao Alto Do Iguacu": "PR",
  "Espirito Santo": "RN",
  "Espirito Santo Do Pinhal": "SP",
  "Espirito Santo Do Turvo": "SP",
  "Esplanada": "BA",
  "Espumoso": "RS",
  "Estacao": "RS",
  "Estancia": "SE",
  "Estancia Velha": "RS",
  "Esteio": "RS",
  "Estiva Gerbi": "SP",
  "Estrela": "RS",
  "Estrela De Alagoas": "AL",
  "Estrela Do Norte": "SP",
  "Estrela Velha": "RS",
  "Euclides Da Cunha": "BA",
  "Euclides Da Cunha Paulista": "SP",
  "Eugenio De Castro": "RS",
  "Eunapolis": "BA",
  "Eusebio": "CE",
  "Extremoz": "RN",
  "Exu": "PE",
  "Fagundes": "PB",
  "Fagundes Varela": "RS",
  "Farias Brito": "CE",
  "Faro": "PA",
  "Farol": "PR",
  "Farroupilha": "RS",
  "Fartura": "SP",
  "Fartura Do Piaui": "PI",
  "Fatima": "TO",
  "Faxinal": "PR",
  "Faxinal Do Soturno": "RS",
  "Faxinal Dos Guedes": "SC",
  "Faxinalzinho": "RS",
  "Fazenda Rio Grande": "PR",
  "Fazenda Vilanova": "RS",
  "Feijo": "AC",
  "Feira Da Mata": "BA",
  "Feira De Santana": "BA",
  "Feira Grande": "AL",
  "Feira Nova": "SE",
  "Felipe Guerra": "RN",
  "Feliz": "RS",
  "Feliz Deserto": "AL",
  "Feliz Natal": "MT",
  "Fenix": "PR",
  "Fernandes Pinheiro": "PR",
  "Fernando De Noronha": "PE",
  "Fernando Pedroza": "RN",
  "Fernando Prestes": "SP",
  "Fernandopolis": "SP",
  "Fernao": "SP",
  "Ferraz De Vasconcelos": "SP",
  "Ferreira Gomes": "AP",
  "Ferreiros": "PE",
  "Figueira": "PR",
  "Figueiropolis": "TO",
  "Filadelfia": "BA",
  "Firmino Alves": "BA",
  "Flexeiras": "AL",
  "Flor Da Serra Do Sul": "PR",
  "Flor Do Sertao": "SC",
  "Flora Rica": "SP",
  "Florai": "PR",
  "Florania": "RN",
  "Floreal": "SP",
  "Flores": "PE",
  "Flores Da Cunha": "RS",
  "Flores Do Piaui": "PI",
  "Floresta": "PE",
  "Floresta Azul": "BA",
  "Floresta Do Araguaia": "PA",
  "Floresta Do Piaui": "PI",
  "Florestopolis": "PR",
  "Floriano": "PI",
  "Floriano Peixoto": "RS",
  "Florianopolis": "SC",
  "Florida": "PR",
  "Florida Paulista": "SP",
  "Florinia": "SP",
  "Fontoura Xavier": "RS",
  "Formigueiro": "RS",
  "Formosa Do Oeste": "PR",
  "Formosa Do Rio Preto": "BA",
  "Formosa Do Sul": "SC",
  "Formoso Do Araguaia": "TO",
  "Forquetinha": "RS",
  "Forquilha": "CE",
  "Forquilhinha": "SC",
  "Fortaleza": "CE",
  "Fortaleza Do Tabocao": "TO",
  "Fortaleza Dos Valos": "RS",
  "Fortim": "CE",
  "Foz Do Iguacu": "PR",
  "Foz Do Jordao": "PR",
  "Fraiburgo": "SC",
  "Franca": "SP",
  "Francinopolis": "PI",
  "Francisco Alves": "PR",
  "Francisco Ayres": "PI",
  "Francisco Beltrao": "PR",
  "Francisco Dantas": "RN",
  "Francisco Macedo": "PI",
  "Francisco Morato": "SP",
  "Francisco Santos": "PI",
  "Franco Da Rocha": "SP",
  "Frecheirinha": "CE",
  "Frederico Westphalen": "RS",
  "Frei Martinho": "PB",
  "Frei Miguelinho": "PE",
  "Frei Paulo": "SE",
  "Frei Rogerio": "SC",
  "Fronteiras": "PI",
  "Frutuoso Gomes": "RN",
  "Fundao": "ES",
  "Gabriel Monteiro": "SP",
  "Gado Bravo": "PB",
  "Galia": "SP",
  "Galinhos": "RN",
  "Galvao": "SC",
  "Gameleira": "PE",
  "Gandu": "BA",
  "Garanhuns": "PE",
  "Gararu": "SE",
  "Garca": "SP",
  "Garibaldi": "RS",
  "Garopaba": "SC",
  "Garrafao Do Norte": "PA",
  "Garruchos": "RS",
  "Garuva": "SC",
  "Gaspar": "SC",
  "Gastao Vidigal": "SP",
  "Gaucha Do Norte": "MT",
  "Gaurama": "RS",
  "Gaviao": "BA",
  "Gaviao Peixoto": "SP",
  "Geminiano": "PI",
  "General Camara": "RS",
  "General Carneiro": "MT",
  "General Maynard": "SE",
  "General Salgado": "SP",
  "General Sampaio": "CE",
  "Gentil": "RS",
  "Gentio Do Ouro": "BA",
  "Getulina": "SP",
  "Getulio Vargas": "RS",
  "Gilbues": "PI",
  "Girau Do Ponciano": "AL",
  "Girua": "RS",
  "Glicerio": "SP",
  "Gloria": "BA",
  "Gloria Do Goita": "PE",
  "Glorinha": "RS",
  "Godoy Moreira": "PR",
  "Goiana": "PE",
  "Goianesia Do Para": "PA",
  "Goianinha": "RN",
  "Goianorte": "TO",
  "Goiatins": "TO",
  "Goioere": "PR",
  "Goioxim": "PR",
  "Gongogi": "BA",
  "Governador Celso Ramos": "SC",
  "Governador Dix-Sept Rosado": "RN",
  "Governador Lindenberg": "ES",
  "Governador Mangabeira": "BA",
  "Graca": "CE",
  "Gracho Cardoso": "SE",
  "Gramado": "RS",
  "Gramado Dos Loureiros": "RS",
  "Gramado Xavier": "RS",
  "Grandes Rios": "PR",
  "Granito": "PE",
  "Granja": "CE",
  "Granjeiro": "CE",
  "Grao Para": "SC",
  "Gravata": "PE",
  "Gravatai": "RS",
  "Gravatal": "SC",
  "Groairas": "CE",
  "Grossos": "RN",
  "Guabiju": "RS",
  "Guabiruba": "SC",
  "Guacui": "ES",
  "Guadalupe": "PI",
  "Guaiba": "RS",
  "Guaicara": "SP",
  "Guaimbe": "SP",
  "Guaira": "SP",
  "Guairaca": "PR",
  "Guaiuba": "CE",
  "Guajeru": "BA",
  "Guamare": "RN",
  "Guamiranga": "PR",
  "Guanambi": "BA",
  "Guapiacu": "SP",
  "Guapiara": "SP",
  "Guapimirim": "RJ",
  "Guapirama": "PR",
  "Guapore": "RS",
  "Guaporema": "PR",
  "Guara": "SP",
  "Guarabira": "PB",
  "Guaracai": "SP",
  "Guaraci": "SP",
  "Guaraciaba": "SC",
  "Guaraciaba Do Norte": "CE",
  "Guarai": "TO",
  "Guaramiranga": "CE",
  "Guaramirim": "SC",
  "Guarani Das Missoes": "RS",
  "Guaraniacu": "PR",
  "Guaranta": "SP",
  "Guaranta Do Norte": "MT",
  "Guarapari": "ES",
  "Guarapuava": "PR",
  "Guaraquecaba": "PR",
  "Guararapes": "SP",
  "Guararema": "SP",
  "Guaratinga": "BA",
  "Guaratingueta": "SP",
  "Guaratuba": "PR",
  "Guarei": "SP",
  "Guariba": "SP",
  "Guaribas": "PI",
  "Guaruja": "SP",
  "Guaruja Do Sul": "SC",
  "Guarulhos": "SP",
  "Guatambu": "SC",
  "Guatapara": "SP",
  "Guiratinga": "MT",
  "Gurinhem": "PB",
  "Gurjao": "PB",
  "Gurupa": "PA",
  "Gurupi": "TO",
  "Guzolandia": "SP",
  "Harmonia": "RS",
  "Heliopolis": "BA",
  "Herculandia": "SP",
  "Herval": "RS",
  "Herveiras": "RS",
  "Hidrolandia": "CE",
  "Holambra": "SP",
  "Honorio Serpa": "PR",
  "Horizonte": "CE",
  "Horizontina": "RS",
  "Hortolandia": "SP",
  "Hugo Napoleao": "PI",
  "Hulha Negra": "RS",
  "Humaita": "RS",
  "Iacanga": "SP",
  "Iacri": "SP",
  "Iacu": "BA",
  "Iaras": "SP",
  "Iati": "PE",
  "Ibaiti": "PR",
  "Ibarama": "RS",
  "Ibaretama": "CE",
  "Ibate": "SP",
  "Ibateguara": "AL",
  "Ibatiba": "ES",
  "Ibema": "PR",
  "Ibiaca": "RS",
  "Ibiam": "SC",
  "Ibiapina": "CE",
  "Ibiara": "PB",
  "Ibiassuce": "BA",
  "Ibicarai": "BA",
  "Ibicare": "SC",
  "Ibicoara": "BA",
  "Ibicui": "BA",
  "Ibicuitinga": "CE",
  "Ibimirim": "PE",
  "Ibipeba": "BA",
  "Ibipitanga": "BA",
  "Ibipora": "PR",
  "Ibiquera": "BA",
  "Ibira": "SP",
  "Ibiracu": "ES",
  "Ibiraiaras": "RS",
  "Ibirajuba": "PE",
  "Ibirama": "SC",
  "Ibirapitanga": "BA",
  "Ibirapua": "BA",
  "Ibirapuita": "RS",
  "Ibirarema": "SP",
  "Ibirataia": "BA",
  "Ibiruba": "RS",
  "Ibitiara": "BA",
  "Ibitinga": "SP",
  "Ibitirama": "ES",
  "Ibitita": "BA",
  "Ibiuna": "SP",
  "Ibotirama": "BA",
  "Icapui": "CE",
  "Icara": "SC",
  "Icaraima": "PR",
  "Icem": "SP",
  "Ichu": "BA",
  "Ico": "CE",
  "Iconha": "ES",
  "Ielmo Marinho": "RN",
  "Iepe": "SP",
  "Igaci": "AL",
  "Igapora": "BA",
  "Igaracu Do Tiete": "SP",
  "Igaracy": "PB",
  "Igarapava": "SP",
  "Igarape-Acu": "PA",
  "Igarape-Miri": "PA",
  "Igarassu": "PE",
  "Igarata": "SP",
  "Igrapiuna": "BA",
  "Igreja Nova": "AL",
  "Igrejinha": "RS",
  "Iguaba Grande": "RJ",
  "Iguai": "BA",
  "Iguape": "SP",
  "Iguaraci": "PE",
  "Iguaracu": "PR",
  "Iguatu": "PR",
  "Ijui": "RS",
  "Ilha Comprida": "SP",
  "Ilha Das Flores": "SE",
  "Ilha De Itamaraca": "PE",
  "Ilha Grande": "PI",
  "Ilha Solteira": "SP",
  "Ilhabela": "SP",
  "Ilheus": "BA",
  "Ilhota": "SC",
  "Ilopolis": "RS",
  "Imaculada": "PB",
  "Imarui": "SC",
  "Imbau": "PR",
  "Imbe": "RS",
  "Imbituba": "SC",
  "Imbituva": "PR",
  "Imbuia": "SC",
  "Imigrante": "RS",
  "Inacio Martins": "PR",
  "Inaja": "PR",
  "Indaial": "SC",
  "Indaiatuba": "SP",
  "Independencia": "CE",
  "Indiana": "SP",
  "Indianopolis": "PR",
  "Indiapora": "SP",
  "Indiaroba": "SE",
  "Indiavai": "MT",
  "Inga": "PB",
  "Ingazeira": "PE",
  "Inhacora": "RS",
  "Inhambupe": "BA",
  "Inhangapi": "PA",
  "Inhapi": "AL",
  "Inhuma": "PI",
  "Inubia Paulista": "SP",
  "Iomere": "SC",
  "Ipanguacu": "RN",
  "Ipaporanga": "CE",
  "Ipaumirim": "CE",
  "Ipaussu": "SP",
  "Ipe": "RS",
  "Ipecaeta": "BA",
  "Ipero": "SP",
  "Ipeuna": "SP",
  "Ipiau": "BA",
  "Ipigua": "SP",
  "Ipira": "BA",
  "Ipiranga": "PR",
  "Ipiranga Do Norte": "MT",
  "Ipiranga Do Piaui": "PI",
  "Ipiranga Do Sul": "RS",
  "Ipixuna Do Para": "PA",
  "Ipojuca": "PE",
  "Ipora": "PR",
  "Ipora Do Oeste": "SC",
  "Iporanga": "SP",
  "Ipu": "CE",
  "Ipua": "SP",
  "Ipuacu": "SC",
  "Ipubi": "PE",
  "Ipueira": "RN",
  "Ipueiras": "TO",
  "Ipumirim": "SC",
  "Ipupiara": "BA",
  "Iracema": "CE",
  "Iracema Do Oeste": "PR",
  "Iracemapolis": "SP",
  "Iraceminha": "SC",
  "Irai": "RS",
  "Irajuba": "BA",
  "Iramaia": "BA",
  "Irani": "SC",
  "Irapua": "SP",
  "Irapuru": "SP",
  "Iraquara": "BA",
  "Irara": "BA",
  "Irati": "PR",
  "Iraucuba": "CE",
  "Irece": "BA",
  "Iretama": "PR",
  "Irineopolis": "SC",
  "Irituia": "PA",
  "Irupi": "ES",
  "Isaias Coelho": "PI",
  "Ita": "SC",
  "Itaara": "RS",
  "Itabaiana": "SE",
  "Itabaianinha": "SE",
  "Itabela": "BA",
  "Itabera": "SP",
  "Itaberaba": "BA",
  "Itabi": "SE",
  "Itaborai": "RJ",
  "Itabuna": "BA",
  "Itacaja": "TO",
  "Itacare": "BA",
  "Itacuruba": "PE",
  "Itacurubi": "RS",
  "Itaete": "BA",
  "Itagi": "BA",
  "Itagiba": "BA",
  "Itagimirim": "BA",
  "Itaguacu": "ES",
  "Itaguacu Da Bahia": "BA",
  "Itaguai": "RJ",
  "Itaguaje": "PR",
  "Itaguatins": "TO",
  "Itai": "SP",
  "Itaiba": "PE",
  "Itaicaba": "CE",
  "Itainopolis": "PI",
  "Itaiopolis": "SC",
  "Itaipulandia": "PR",
  "Itaitinga": "CE",
  "Itaituba": "PA",
  "Itaja": "RN",
  "Itajai": "SC",
  "Itajobi": "SP",
  "Itaju": "SP",
  "Itaju Do Colonia": "BA",
  "Itajuipe": "BA",
  "Italva": "RJ",
  "Itamaraju": "BA",
  "Itamari": "BA",
  "Itambaraca": "PR",
  "Itambe": "PE",
  "Itanagra": "BA",
  "Itanhaem": "SP",
  "Itanhangá": "MT",
  "Itanhem": "BA",
  "Itaoca": "SP",
  "Itaocara": "RJ",
  "Itapage": "CE",
  "Itaparica": "BA",
  "Itape": "BA",
  "Itapebi": "BA",
  "Itapecerica Da Serra": "SP",
  "Itapema": "SC",
  "Itapemirim": "ES",
  "Itaperucu": "PR",
  "Itaperuna": "RJ",
  "Itapetim": "PE",
  "Itapetinga": "BA",
  "Itapetininga": "SP",
  "Itapeva": "SP",
  "Itapevi": "SP",
  "Itapicuru": "BA",
  "Itapipoca": "CE",
  "Itapira": "SP",
  "Itapiranga": "SC",
  "Itapirapua Paulista": "SP",
  "Itapiratins": "TO",
  "Itapissuma": "PE",
  "Itapitanga": "BA",
  "Itapiuna": "CE",
  "Itapoa": "SC",
  "Itapolis": "SP",
  "Itapora Do Tocantins": "TO",
  "Itaporanga": "PB",
  "Itapororoca": "PB",
  "Itapuca": "RS",
  "Itapui": "SP",
  "Itapura": "SP",
  "Itaquaquecetuba": "SP",
  "Itaquara": "BA",
  "Itaqui": "RS",
  "Itaquitinga": "PE",
  "Itarana": "ES",
  "Itarantim": "BA",
  "Itarare": "SP",
  "Itarema": "CE",
  "Itariri": "SP",
  "Itati": "RS",
  "Itatiaia": "RJ",
  "Itatiba": "SP",
  "Itatiba Do Sul": "RS",
  "Itatim": "BA",
  "Itatinga": "SP",
  "Itatira": "CE",
  "Itatuba": "PB",
  "Itau": "RN",
  "Itauba": "MT",
  "Itaubal": "AP",
  "Itaueira": "PI",
  "Itauna Do Sul": "PR",
  "Itiquira": "MT",
  "Itirapina": "SP",
  "Itirapua": "SP",
  "Itirucu": "BA",
  "Itiuba": "BA",
  "Itobi": "SP",
  "Itororo": "BA",
  "Itu": "SP",
  "Ituacu": "BA",
  "Itubera": "BA",
  "Itupeva": "SP",
  "Itupiranga": "PA",
  "Ituporanga": "SC",
  "Ituverava": "SP",
  "Iuiu": "BA",
  "Iuna": "ES",
  "Ivai": "PR",
  "Ivaipora": "PR",
  "Ivate": "PR",
  "Ivatuba": "PR",
  "Ivora": "RS",
  "Ivoti": "RS",
  "Jaboatao Dos Guararapes": "PE",
  "Jabora": "SC",
  "Jaborandi": "BA",
  "Jaboti": "PR",
  "Jaboticaba": "RS",
  "Jaboticabal": "SP",
  "Jacana": "RN",
  "Jacaraci": "BA",
  "Jacarau": "PB",
  "Jacare Dos Homens": "AL",
  "Jacareacanga": "PA",
  "Jacarei": "SP",
  "Jacarezinho": "PR",
  "Jaci": "SP",
  "Jaciara": "MT",
  "Jacinto Machado": "SC",
  "Jacobina": "BA",
  "Jacobina Do Piaui": "PI",
  "Jacuipe": "AL",
  "Jacuizinho": "RS",
  "Jacunda": "PA",
  "Jacupiranga": "SP",
  "Jacutinga": "RS",
  "Jaguapita": "PR",
  "Jaguaquara": "BA",
  "Jaguarao": "RS",
  "Jaguarari": "BA",
  "Jaguare": "ES",
  "Jaguaretama": "CE",
  "Jaguari": "RS",
  "Jaguariaiva": "PR",
  "Jaguaribara": "CE",
  "Jaguaribe": "CE",
  "Jaguaripe": "BA",
  "Jaguariuna": "SP",
  "Jaguaruana": "CE",
  "Jaguaruna": "SC",
  "Jaicos": "PI",
  "Jales": "SP",
  "Jambeiro": "SP",
  "Jandaia Do Sul": "PR",
  "Jandaira": "BA",
  "Jandira": "SP",
  "Janduis": "RN",
  "Jangada": "MT",
  "Janiopolis": "PR",
  "Januario Cicco": "RN",
  "Japaratinga": "AL",
  "Japaratuba": "SE",
  "Japeri": "RJ",
  "Japi": "RN",
  "Japira": "PR",
  "Japoata": "SE",
  "Japura": "PR",
  "Jaqueira": "PE",
  "Jaquirana": "RS",
  "Jaragua Do Sul": "SC",
  "Jaramataia": "AL",
  "Jardim": "CE",
  "Jardim Alegre": "PR",
  "Jardim De Angicos": "RN",
  "Jardim De Piranhas": "RN",
  "Jardim Do Mulato": "PI",
  "Jardim Do Serido": "RN",
  "Jardim Olinda": "PR",
  "Jardinopolis": "SP",
  "Jari": "RS",
  "Jarinu": "SP",
  "Jataizinho": "PR",
  "Jatauba": "PE",
  "Jati": "CE",
  "Jatoba": "PE",
  "Jatoba Do Piaui": "PI",
  "Jau": "SP",
  "Jau Do Tocantins": "TO",
  "Jauru": "MT",
  "Jequie": "BA",
  "Jequiá Da Praia": "AL",
  "Jeremoabo": "BA",
  "Jerico": "PB",
  "Jeriquara": "SP",
  "Jeronimo Monteiro": "ES",
  "Jerumenha": "PI",
  "Jesuitas": "PR",
  "Jijoca De Jericoacoara": "CE",
  "Jiquirica": "BA",
  "Jitauna": "BA",
  "Joacaba": "SC",
  "Joanopolis": "SP",
  "Joao Alfredo": "PE",
  "Joao Camara": "RN",
  "Joao Costa": "PI",
  "Joao Dias": "RN",
  "Joao Dourado": "BA",
  "Joao Neiva": "ES",
  "Joao Pessoa": "PB",
  "Joao Ramalho": "SP",
  "Joaquim Gomes": "AL",
  "Joaquim Nabuco": "PE",
  "Joaquim Pires": "PI",
  "Joaquim Tavora": "PR",
  "Joca Marques": "PI",
  "Joia": "RS",
  "Joinville": "SC",
  "Jordao": "AC",
  "Jose Boiteux": "SC",
  "Jose Bonifacio": "SP",
  "Jose Da Penha": "RN",
  "Jose De Freitas": "PI",
  "Juara": "MT",
  "Juarez Tavora": "PB",
  "Juarina": "TO",
  "Juazeirinho": "PB",
  "Juazeiro": "BA",
  "Juazeiro Do Norte": "CE",
  "Juazeiro Do Piaui": "PI",
  "Jucas": "CE",
  "Jucati": "PE",
  "Jucurucu": "BA",
  "Jucurutu": "RN",
  "Juina": "MT",
  "Julio Borges": "PI",
  "Julio De Castilhos": "RS",
  "Julio Mesquita": "SP",
  "Jumirim": "SP",
  "Junco Do Serido": "PB",
  "Jundia": "AL",
  "Jundiai": "SP",
  "Jundiai Do Sul": "PR",
  "Jundiá": "RN",
  "Junqueiro": "AL",
  "Junqueiropolis": "SP",
  "Jupi": "PE",
  "Jupia": "SC",
  "Juquia": "SP",
  "Juquitiba": "SP",
  "Juranda": "PR",
  "Jurema": "PI",
  "Juripiranga": "PB",
  "Juru": "PB",
  "Juruena": "MT",
  "Juruti": "PA",
  "Juscimeira": "MT",
  "Jussara": "PR",
  "Jussari": "BA",
  "Jussiape": "BA",
  "Kalore": "PR",
  "Lacerdopolis": "SC",
  "Lafaiete Coutinho": "BA",
  "Lagarto": "SE",
  "Lages": "SC",
  "Lagoa": "PB",
  "Lagoa Alegre": "PI",
  "Lagoa Bonita Do Sul": "RS",
  "Lagoa Da Canoa": "AL",
  "Lagoa Da Confusao": "TO",
  "Lagoa De Dentro": "PB",
  "Lagoa De Pedras": "RN",
  "Lagoa De Sao Francisco": "PI",
  "Lagoa De Velhos": "RN",
  "Lagoa Do Barro Do Piaui": "PI",
  "Lagoa Do Carro": "PE",
  "Lagoa Do Itaenga": "PE",
  "Lagoa Do Ouro": "PE",
  "Lagoa Do Piaui": "PI",
  "Lagoa Do Sitio": "PI",
  "Lagoa Do Tocantins": "TO",
  "Lagoa Dos Gatos": "PE",
  "Lagoa Dos Tres Cantos": "RS",
  "Lagoa Grande": "PE",
  "Lagoa Nova": "RN",
  "Lagoa Real": "BA",
  "Lagoa Salgada": "RN",
  "Lagoa Seca": "PB",
  "Lagoa Vermelha": "RS",
  "Lagoao": "RS",
  "Lagoinha": "SP",
  "Lagoinha Do Piaui": "PI",
  "Laguna": "SC",
  "Laje": "BA",
  "Laje Do Muriae": "RJ",
  "Lajeado": "RS",
  "Lajeado Do Bugre": "RS",
  "Lajeado Grande": "SC",
  "Lajedao": "BA",
  "Lajedinho": "BA",
  "Lajedo": "PE",
  "Lajedo Do Tabocal": "BA",
  "Lajes": "RN",
  "Lajes Pintadas": "RN",
  "Lamarao": "BA",
  "Landri Sales": "PI",
  "Lapa": "PR",
  "Lapao": "BA",
  "Laranja Da Terra": "ES",
  "Laranjal": "PR",
  "Laranjal Do Jari": "AP",
  "Laranjal Paulista": "SP",
  "Laranjeiras": "SE",
  "Laranjeiras Do Sul": "PR",
  "Lastro": "PB",
  "Laurentino": "SC",
  "Lauro De Freitas": "BA",
  "Lauro Muller": "SC",
  "Lavandeira": "TO",
  "Lavinia": "SP",
  "Lavras Da Mangabeira": "CE",
  "Lavras Do Sul": "RS",
  "Lavrinhas": "SP",
  "Lebon Regis": "SC",
  "Leme": "SP",
  "Lencois": "BA",
  "Lencois Paulista": "SP",
  "Leoberto Leal": "SC",
  "Leopolis": "PR",
  "Liberato Salzano": "RS",
  "Licinio De Almeida": "BA",
  "Lidianopolis": "PR",
  "Limeira": "SP",
  "Limoeiro": "PE",
  "Limoeiro De Anadia": "AL",
  "Limoeiro Do Ajuru": "PA",
  "Limoeiro Do Norte": "CE",
  "Lindoeste": "PR",
  "Lindoia": "SP",
  "Lindoia Do Sul": "SC",
  "Lindolfo Collor": "RS",
  "Linha Nova": "RS",
  "Linhares": "ES",
  "Lins": "SP",
  "Livramento": "PB",
  "Livramento De Nossa Senhora": "BA",
  "Lizarda": "TO",
  "Loanda": "PR",
  "Lobato": "PR",
  "Logradouro": "PB",
  "Londrina": "PR",
  "Lontras": "SC",
  "Lorena": "SP",
  "Lourdes": "SP",
  "Louveira": "SP",
  "Lucas Do Rio Verde": "MT",
  "Lucelia": "SP",
  "Lucena": "PB",
  "Lucianopolis": "SP",
  "Luciara": "MT",
  "Lucrecia": "RN",
  "Luis Antonio": "SP",
  "Luis Correia": "PI",
  "Luis Eduardo Magalhaes": "BA",
  "Luis Gomes": "RN",
  "Luiz Alves": "SC",
  "Luiziana": "PR",
  "Luiziania": "SP",
  "Lunardelli": "PR",
  "Lupercio": "SP",
  "Lupionopolis": "PR",
  "Lutecia": "SP",
  "Luzerna": "SC",
  "Luzilandia": "PI",
  "Luzinopolis": "TO",
  "Macae": "RJ",
  "Macaiba": "RN",
  "Macajuba": "BA",
  "Macambara": "RS",
  "Macambira": "SE",
  "Macapa": "AP",
  "Macaparana": "PE",
  "Macarani": "BA",
  "Macatuba": "SP",
  "Macau": "RN",
  "Macaubal": "SP",
  "Macaubas": "BA",
  "Macedonia": "SP",
  "Maceio": "AL",
  "Machadinho": "RS",
  "Machados": "PE",
  "Macieira": "SC",
  "Macuco": "RJ",
  "Macurure": "BA",
  "Madalena": "CE",
  "Madeiro": "PI",
  "Madre De Deus": "BA",
  "Mae Do Rio": "PA",
  "Maetinga": "BA",
  "Mafra": "SC",
  "Magalhaes Barata": "PA",
  "Magda": "SP",
  "Mage": "RJ",
  "Maiquinique": "BA",
  "Mairi": "BA",
  "Mairinque": "SP",
  "Mairipora": "SP",
  "Major Gercino": "SC",
  "Major Isidoro": "AL",
  "Major Sales": "RN",
  "Major Vieira": "SC",
  "Malhada": "BA",
  "Malhada De Pedras": "BA",
  "Malhada Dos Bois": "SE",
  "Malhador": "SE",
  "Mallet": "PR",
  "Malta": "PB",
  "Mamanguape": "PB",
  "Mambore": "PR",
  "Mampituba": "RS",
  "Manaira": "PB",
  "Manari": "PE",
  "Mancio Lima": "AC",
  "Mandaguacu": "PR",
  "Mandaguari": "PR",
  "Mandirituba": "PR",
  "Manduri": "SP",
  "Manfrinopolis": "PR",
  "Mangaratiba": "RJ",
  "Mangueirinha": "PR",
  "Manoel Emidio": "PI",
  "Manoel Ribas": "PR",
  "Manoel Urbano": "AC",
  "Manoel Viana": "RS",
  "Manoel Vitorino": "BA",
  "Mansidao": "BA",
  "Mantenopolis": "ES",
  "Maquine": "RS",
  "Mar Vermelho": "AL",
  "Maraba": "PA",
  "Maraba Paulista": "SP",
  "Maracai": "SP",
  "Maracaja": "SC",
  "Maracana": "PA",
  "Maracanau": "CE",
  "Maracas": "BA",
  "Maragogi": "AL",
  "Maragogipe": "BA",
  "Maraial": "PE",
  "Maranguape": "CE",
  "Marapanim": "PA",
  "Marapoama": "SP",
  "Marata": "RS",
  "Marataizes": "ES",
  "Marau": "RS",
  "Maravilha": "AL",
  "Marcacao": "PB",
  "Marcelandia": "MT",
  "Marcelino Ramos": "RS",
  "Marcelino Vieira": "RN",
  "Marcionilio Souza": "BA",
  "Marco": "CE",
  "Marcolandia": "PI",
  "Marcos Parente": "PI",
  "Marechal Candido Rondon": "PR",
  "Marechal Deodoro": "AL",
  "Marechal Floriano": "ES",
  "Marechal Thaumaturgo": "AC",
  "Marema": "SC",
  "Mari": "PB",
  "Maria Helena": "PR",
  "Marialva": "PR",
  "Mariana Pimentel": "RS",
  "Mariano Moro": "RS",
  "Marianopolis Do Tocantins": "TO",
  "Mariapolis": "SP",
  "Maribondo": "AL",
  "Marica": "RJ",
  "Marilandia": "ES",
  "Marilandia Do Sul": "PR",
  "Marilena": "PR",
  "Marilia": "SP",
  "Mariluz": "PR",
  "Maringa": "PR",
  "Marinopolis": "SP",
  "Mariopolis": "PR",
  "Maripa": "PR",
  "Marituba": "PA",
  "Marizopolis": "PB",
  "Marmeleiro": "PR",
  "Marques De Souza": "RS",
  "Marquinho": "PR",
  "Martinopole": "CE",
  "Martinopolis": "SP",
  "Martins": "RN",
  "Maruim": "SE",
  "Marumbi": "PR",
  "Mascote": "BA",
  "Massape": "CE",
  "Massape Do Piaui": "PI",
  "Massaranduba": "PB",
  "Mata": "RS",
  "Mata De Sao Joao": "BA",
  "Mata Grande": "AL",
  "Matao": "SP",
  "Mataraca": "PB",
  "Mateiros": "TO",
  "Matelandia": "PR",
  "Matias Olimpio": "PI",
  "Matina": "BA",
  "Matinhas": "PB",
  "Matinhos": "PR",
  "Mato Castelhano": "RS",
  "Mato Grosso": "PB",
  "Mato Leitao": "RS",
  "Mato Queimado": "RS",
  "Mato Rico": "PR",
  "Matos Costa": "SC",
  "Matriz De Camaragibe": "AL",
  "Matupa": "MT",
  "Matureia": "PB",
  "Maua": "SP",
  "Maua Da Serra": "PR",
  "Maurilandia Do Tocantins": "TO",
  "Mauriti": "CE",
  "Maxaranguape": "RN",
  "Maximiliano De Almeida": "RS",
  "Mazagao": "AP",
  "Medeiros Neto": "BA",
  "Medianeira": "PR",
  "Medicilandia": "PA",
  "Meleiro": "SC",
  "Melgaco": "PA",
  "Mendes": "RJ",
  "Mendonca": "SP",
  "Mercedes": "PR",
  "Meridiano": "SP",
  "Meruoca": "CE",
  "Mesopolis": "SP",
  "Mesquita": "RJ",
  "Messias": "AL",
  "Messias Targino": "RN",
  "Miguel Alves": "PI",
  "Miguel Calmon": "BA",
  "Miguel Leao": "PI",
  "Miguel Pereira": "RJ",
  "Miguelopolis": "SP",
  "Milagres": "BA",
  "Milha": "CE",
  "Milton Brandao": "PI",
  "Mimoso Do Sul": "ES",
  "Minador Do Negrao": "AL",
  "Minas Do Leao": "RS",
  "Mineiros Do Tiete": "SP",
  "Mira Estrela": "SP",
  "Miracatu": "SP",
  "Miracema": "RJ",
  "Miracema Do Tocantins": "TO",
  "Mirador": "PR",
  "Miraguai": "RS",
  "Miraima": "CE",
  "Mirandiba": "PE",
  "Mirandopolis": "SP",
  "Mirangaba": "BA",
  "Miranorte": "TO",
  "Mirante": "BA",
  "Mirante Do Paranapanema": "SP",
  "Miraselva": "PR",
  "Mirassol": "SP",
  "Mirassolandia": "SP",
  "Mirim Doce": "SC",
  "Missal": "PR",
  "Missao Velha": "CE",
  "Mocajuba": "PA",
  "Mococa": "SP",
  "Modelo": "SC",
  "Mogeiro": "PB",
  "Mogi Das Cruzes": "SP",
  "Mogi Guacu": "SP",
  "Moita Bonita": "SE",
  "Moji Mirim": "SP",
  "Moju": "PA",
  "Mombaca": "CE",
  "Mombuca": "SP",
  "Moncoes": "SP",
  "Mondai": "SC",
  "Mongagua": "SP",
  "Monsenhor Gil": "PI",
  "Monsenhor Hipolito": "PI",
  "Monsenhor Tabosa": "CE",
  "Montadas": "PB",
  "Montanha": "ES",
  "Montanhas": "RN",
  "Montauri": "RS",
  "Monte Alegre": "PA",
  "Monte Alegre De Sergipe": "SE",
  "Monte Alegre Do Piaui": "PI",
  "Monte Alegre Do Sul": "SP",
  "Monte Alegre Dos Campos": "RS",
  "Monte Alto": "SP",
  "Monte Aprazivel": "SP",
  "Monte Azul Paulista": "SP",
  "Monte Belo Do Sul": "RS",
  "Monte Carlo": "SC",
  "Monte Castelo": "SP",
  "Monte Das Gameleiras": "RN",
  "Monte Do Carmo": "TO",
  "Monte Horebe": "PB",
  "Monte Mor": "SP",
  "Monte Santo": "BA",
  "Monte Santo Do Tocantins": "TO",
  "Monteiro": "PB",
  "Monteiro Lobato": "SP",
  "Monteiropolis": "AL",
  "Montenegro": "RS",
  "Morada Nova": "CE",
  "Moraujo": "CE",
  "Moreilandia": "PE",
  "Moreira Sales": "PR",
  "Moreno": "PE",
  "Mormaco": "RS",
  "Morpara": "BA",
  "Morretes": "PR",
  "Morrinhos": "CE",
  "Morrinhos Do Sul": "RS",
  "Morro Agudo": "SP",
  "Morro Cabeca No Tempo": "PI",
  "Morro Da Fumaca": "SC",
  "Morro Do Chapeu": "BA",
  "Morro Do Chapeu Do Piaui": "PI",
  "Morro Grande": "SC",
  "Morro Redondo": "RS",
  "Morro Reuter": "RS",
  "Mortugaba": "BA",
  "Morungaba": "SP",
  "Mossoro": "RN",
  "Mostardas": "RS",
  "Motuca": "SP",
  "Muana": "PA",
  "Mucajai": "RR",
  "Mucambo": "CE",
  "Mucuge": "BA",
  "Mucum": "RS",
  "Mucuri": "BA",
  "Mucurici": "ES",
  "Muitos Capoes": "RS",
  "Muliterno": "RS",
  "Mulungu": "CE",
  "Mulungu Do Morro": "BA",
  "Mundo Novo": "BA",
  "Munhoz De Melo": "PR",
  "Muniz Ferreira": "BA",
  "Muniz Freire": "ES",
  "Muquem De Sao Francisco": "BA",
  "Muqui": "ES",
  "Muribeca": "SE",
  "Murici": "AL",
  "Murici Dos Portelas": "PI",
  "Muricilandia": "TO",
  "Muritiba": "BA",
  "Murutinga Do Sul": "SP",
  "Mutuipe": "BA",
  "Nantes": "SP",
  "Nao-Me-Toque": "RS",
  "Narandiba": "SP",
  "Natal": "RN",
  "Natividade": "TO",
  "Natividade Da Serra": "SP",
  "Natuba": "PB",
  "Navegantes": "SC",
  "Nazare": "TO",
  "Nazare Da Mata": "PE",
  "Nazare Do Piaui": "PI",
  "Nazare Paulista": "SP",
  "Nazarezinho": "PB",
  "Neopolis": "SE",
  "Neves Paulista": "SP",
  "Nhandeara": "SP",
  "Nicolau Vergueiro": "RS",
  "Nilo Pecanha": "BA",
  "Nilopolis": "RJ",
  "Nipoa": "SP",
  "Nisia Floresta": "RN",
  "Niteroi": "RJ",
  "Nobres": "MT",
  "Nonoai": "RS",
  "Nordestina": "BA",
  "Normandia": "RR",
  "Nortelandia": "MT",
  "Nossa Senhora Aparecida": "SE",
  "Nossa Senhora Da Gloria": "SE",
  "Nossa Senhora Das Dores": "SE",
  "Nossa Senhora Das Gracas": "PR",
  "Nossa Senhora De Lourdes": "SE",
  "Nossa Senhora De Nazare": "PI",
  "Nossa Senhora Do Livramento": "MT",
  "Nossa Senhora Do Socorro": "SE",
  "Nossa Senhora Dos Remedios": "PI",
  "Nova Alianca": "SP",
  "Nova Alianca Do Ivai": "PR",
  "Nova Alvorada": "RS",
  "Nova America Da Colina": "PR",
  "Nova Araca": "RS",
  "Nova Aurora": "PR",
  "Nova Bandeirantes": "MT",
  "Nova Bassano": "RS",
  "Nova Boa Vista": "RS",
  "Nova Brasilandia": "MT",
  "Nova Brescia": "RS",
  "Nova Campina": "SP",
  "Nova Canaa": "BA",
  "Nova Canaa Do Norte": "MT",
  "Nova Canaa Paulista": "SP",
  "Nova Candelaria": "RS",
  "Nova Cantu": "PR",
  "Nova Castilho": "SP",
  "Nova Cruz": "RN",
  "Nova Erechim": "SC",
  "Nova Esperanca": "PR",
  "Nova Esperanca Do Piria": "PA",
  "Nova Esperanca Do Sudoeste": "PR",
  "Nova Esperanca Do Sul": "RS",
  "Nova Europa": "SP",
  "Nova Fatima": "BA",
  "Nova Floresta": "PB",
  "Nova Friburgo": "RJ",
  "Nova Granada": "SP",
  "Nova Guarita": "MT",
  "Nova Guataporanga": "SP",
  "Nova Hartz": "RS",
  "Nova Ibia": "BA",
  "Nova Iguacu": "RJ",
  "Nova Independencia": "SP",
  "Nova Ipixuna": "PA",
  "Nova Itaberaba": "SC",
  "Nova Itarana": "BA",
  "Nova Lacerda": "MT",
  "Nova Laranjeiras": "PR",
  "Nova Londrina": "PR",
  "Nova Luzitania": "SP",
  "Nova Marilandia": "MT",
  "Nova Maringa": "MT",
  "Nova Monte Verde": "MT",
  "Nova Mutum": "MT",
  "Nova Odessa": "SP",
  "Nova Olimpia": "MT",
  "Nova Olinda": "PB",
  "Nova Padua": "RS",
  "Nova Palma": "RS",
  "Nova Palmeira": "PB",
  "Nova Petropolis": "RS",
  "Nova Prata": "RS",
  "Nova Prata Do Iguacu": "PR",
  "Nova Ramada": "RS",
  "Nova Redencao": "BA",
  "Nova Roma Do Sul": "RS",
  "Nova Rosalandia": "TO",
  "Nova Russas": "CE",
  "Nova Santa Barbara": "PR",
  "Nova Santa Helena": "MT",
  "Nova Santa Rita": "RS",
  "Nova Santa Rosa": "PR",
  "Nova Soure": "BA",
  "Nova Tebas": "PR",
  "Nova Timboteua": "PA",
  "Nova Trento": "SC",
  "Nova Ubirata": "MT",
  "Nova Venecia": "ES",
  "Nova Veneza": "SC",
  "Nova Vicosa": "BA",
  "Nova Xavantina": "MT",
  "Novais": "SP",
  "Novo Acordo": "TO",
  "Novo Alegre": "TO",
  "Novo Barreiro": "RS",
  "Novo Cabrais": "RS",
  "Novo Hamburgo": "RS",
  "Novo Horizonte": "SC",
  "Novo Horizonte Do Norte": "MT",
  "Novo Itacolomi": "PR",
  "Novo Jardim": "TO",
  "Novo Lino": "AL",
  "Novo Machado": "RS",
  "Novo Mundo": "MT",
  "Novo Oriente": "CE",
  "Novo Oriente Do Piaui": "PI",
  "Novo Progresso": "PA",
  "Novo Repartimento": "PA",
  "Novo Santo Antonio": "PI",
  "Novo Sao Joaquim": "MT",
  "Novo Tiradentes": "RS",
  "Novo Triunfo": "BA",
  "Novo Xingu": "RS",
  "Nuporanga": "SP",
  "Obidos": "PA",
  "Ocara": "CE",
  "Ocaucu": "SP",
  "Oeiras": "PI",
  "Oeiras Do Para": "PA",
  "Oiapoque": "AP",
  "Oleo": "SP",
  "Olimpia": "SP",
  "Olinda": "PE",
  "Olindina": "BA",
  "Olivedos": "PB",
  "Oliveira De Fatima": "TO",
  "Oliveira Dos Brejinhos": "BA",
  "Olivenca": "AL",
  "Onda Verde": "SP",
  "Oriente": "SP",
  "Orindiuva": "SP",
  "Oriximina": "PA",
  "Orlandia": "SP",
  "Orleans": "SC",
  "Orobo": "PE",
  "Oroco": "PE",
  "Oros": "CE",
  "Ortigueira": "PR",
  "Osasco": "SP",
  "Oscar Bressane": "SP",
  "Osorio": "RS",
  "Osvaldo Cruz": "SP",
  "Otacilio Costa": "SC",
  "Ourem": "PA",
  "Ouricangas": "BA",
  "Ouricuri": "PE",
  "Ourilandia Do Norte": "PA",
  "Ourinhos": "SP",
  "Ourizona": "PR",
  "Ouro": "SC",
  "Ouro Branco": "RN",
  "Ouro Velho": "PB",
  "Ouro Verde": "SP",
  "Ouro Verde Do Oeste": "PR",
  "Ouroeste": "SP",
  "Ourolandia": "BA",
  "Pacaembu": "SP",
  "Pacaja": "PA",
  "Pacajus": "CE",
  "Pacaraima": "RR",
  "Pacatuba": "SE",
  "Pacoti": "CE",
  "Pacuja": "CE",
  "Padre Marcos": "PI",
  "Paes Landim": "PI",
  "Paial": "SC",
  "Paicandu": "PR",
  "Paim Filho": "RS",
  "Painel": "SC",
  "Pajeu Do Piaui": "PI",
  "Palestina": "AL",
  "Palestina Do Para": "PA",
  "Palhano": "CE",
  "Palhoca": "SC",
  "Palma Sola": "SC",
  "Palmacia": "CE",
  "Palmares": "PE",
  "Palmares Do Sul": "RS",
  "Palmares Paulista": "SP",
  "Palmas": "PR",
  "Palmas De Monte Alto": "BA",
  "Palmeira": "SC",
  "Palmeira Das Missoes": "RS",
  "Palmeira Do Piaui": "PI",
  "Palmeira Dos Indios": "AL",
  "Palmeirais": "PI",
  "Palmeirante": "TO",
  "Palmeiras": "BA",
  "Palmeiras Do Tocantins": "TO",
  "Palmeirina": "PE",
  "Palmeiropolis": "TO",
  "Palmital": "SP",
  "Palmitinho": "RS",
  "Palmitos": "SC",
  "Palotina": "PR",
  "Panambi": "RS",
  "Pancas": "ES",
  "Panelas": "PE",
  "Panorama": "SP",
  "Pantano Grande": "RS",
  "Pao De Acucar": "AL",
  "Papanduva": "SC",
  "Paqueta": "PI",
  "Paracambi": "RJ",
  "Paracuru": "CE",
  "Paragominas": "PA",
  "Paraguacu Paulista": "SP",
  "Parai": "RS",
  "Paraiba Do Sul": "RJ",
  "Paraibuna": "SP",
  "Paraipaba": "CE",
  "Paraiso": "SC",
  "Paraiso Do Norte": "PR",
  "Paraiso Do Sul": "RS",
  "Paraiso Do Tocantins": "TO",
  "Parambu": "CE",
  "Paramirim": "BA",
  "Paramoti": "CE",
  "Parana": "TO",
  "Paranacity": "PR",
  "Paranagua": "PR",
  "Paranaita": "MT",
  "Paranapanema": "SP",
  "Paranapoema": "PR",
  "Paranapua": "SP",
  "Paranatama": "PE",
  "Paranatinga": "MT",
  "Paranavai": "PR",
  "Parapua": "SP",
  "Parari": "PB",
  "Parati": "RJ",
  "Paratinga": "BA",
  "Parau": "RN",
  "Parauapebas": "PA",
  "Parazinho": "RN",
  "Pardinho": "SP",
  "Pareci Novo": "RS",
  "Parelhas": "RN",
  "Pariconha": "AL",
  "Paripiranga": "BA",
  "Paripueira": "AL",
  "Pariquera-Acu": "SP",
  "Parisi": "SP",
  "Parnagua": "PI",
  "Parnaiba": "PI",
  "Parnamirim": "RN",
  "Parobe": "RS",
  "Passa E Fica": "RN",
  "Passa Sete": "RS",
  "Passagem": "PB",
  "Passagem Franca Do Piaui": "PI",
  "Passira": "PE",
  "Passo De Camaragibe": "AL",
  "Passo De Torres": "SC",
  "Passo Do Sobrado": "RS",
  "Passo Fundo": "RS",
  "Passos Maia": "SC",
  "Pato Bragado": "PR",
  "Pato Branco": "PR",
  "Patos": "PB",
  "Patos Do Piaui": "PI",
  "Patrocinio Paulista": "SP",
  "Patu": "RN",
  "Paty Do Alferes": "RJ",
  "Pau Brasil": "BA",
  "Pau Dos Ferros": "RN",
  "Paudalho": "PE",
  "Paula Freitas": "PR",
  "Pauliceia": "SP",
  "Paulinia": "SP",
  "Paulista": "PE",
  "Paulistana": "PI",
  "Paulistania": "SP",
  "Paulo Afonso": "BA",
  "Paulo Bento": "RS",
  "Paulo De Faria": "SP",
  "Paulo Frontin": "PR",
  "Paulo Jacinto": "AL",
  "Paulo Lopes": "SC",
  "Paverama": "RS",
  "Pavussu": "PI",
  "Pe De Serra": "BA",
  "Peabiru": "PR",
  "Pederneiras": "SP",
  "Pedra": "PE",
  "Pedra Bela": "SP",
  "Pedra Branca": "PB",
  "Pedra Branca Do Amapari": "AP",
  "Pedra Grande": "RN",
  "Pedra Lavrada": "PB",
  "Pedra Mole": "SE",
  "Pedra Preta": "MT",
  "Pedranopolis": "SP",
  "Pedrao": "BA",
  "Pedras Altas": "RS",
  "Pedras De Fogo": "PB",
  "Pedras Grandes": "SC",
  "Pedregulho": "SP",
  "Pedreira": "SP",
  "Pedrinhas": "SE",
  "Pedrinhas Paulista": "SP",
  "Pedro Afonso": "TO",
  "Pedro Alexandre": "BA",
  "Pedro Avelino": "RN",
  "Pedro Canario": "ES",
  "Pedro De Toledo": "SP",
  "Pedro Ii": "PI",
  "Pedro Laurentino": "PI",
  "Pedro Osorio": "RS",
  "Pedro Regis": "PB",
  "Pedro Velho": "RN",
  "Peixe": "TO",
  "Peixe-Boi": "PA",
  "Peixoto De Azevedo": "MT",
  "Pejucara": "RS",
  "Pelotas": "RS",
  "Penaforte": "CE",
  "Penapolis": "SP",
  "Pendencias": "RN",
  "Penedo": "AL",
  "Penha": "SC",
  "Pentecoste": "CE",
  "Pequizeiro": "TO",
  "Pereira Barreto": "SP",
  "Pereiras": "SP",
  "Pereiro": "CE",
  "Peritiba": "SC",
  "Perobal": "PR",
  "Perola": "PR",
  "Peruibe": "SP",
  "Pesqueira": "PE",
  "Petrolandia": "PE",
  "Petrolina": "PE",
  "Petropolis": "RJ",
  "Piacabucu": "AL",
  "Piacatu": "SP",
  "Pianco": "PB",
  "Piata": "BA",
  "Picada Cafe": "RS",
  "Picarra": "PA",
  "Picarras": "SC",
  "Picos": "PI",
  "Picui": "PB",
  "Piedade": "SP",
  "Pien": "PR",
  "Pilao Arcado": "BA",
  "Pilar": "AL",
  "Pilar Do Sul": "SP",
  "Piloes": "PB",
  "Piloezinhos": "PB",
  "Pimenteiras": "PI",
  "Pindai": "BA",
  "Pindamonhangaba": "SP",
  "Pindoba": "AL",
  "Pindobacu": "BA",
  "Pindorama": "SP",
  "Pindorama Do Tocantins": "TO",
  "Pindoretama": "CE",
  "Pinhais": "PR",
  "Pinhal": "RS",
  "Pinhal Da Serra": "RS",
  "Pinhal De Sao Bento": "PR",
  "Pinhal Grande": "RS",
  "Pinhalao": "PR",
  "Pinhalzinho": "SP",
  "Pinhao": "SE",
  "Pinheiral": "RJ",
  "Pinheirinho Do Vale": "RS",
  "Pinheiro Machado": "RS",
  "Pinheiro Preto": "SC",
  "Pinheiros": "ES",
  "Pintadas": "BA",
  "Pio Ix": "PI",
  "Piquerobi": "SP",
  "Piquet Carneiro": "CE",
  "Piquete": "SP",
  "Piracaia": "SP",
  "Piracicaba": "SP",
  "Piracuruca": "PI",
  "Pirai": "RJ",
  "Pirai Do Norte": "BA",
  "Pirai Do Sul": "PR",
  "Piraju": "SP",
  "Pirajui": "SP",
  "Pirambu": "SE",
  "Pirangi": "SP",
  "Piranhas": "AL",
  "Pirapo": "RS",
  "Pirapora Do Bom Jesus": "SP",
  "Pirapozinho": "SP",
  "Piraquara": "PR",
  "Piraque": "TO",
  "Pirassununga": "SP",
  "Piratini": "RS",
  "Piratininga": "SP",
  "Piratuba": "SC",
  "Pires Ferreira": "CE",
  "Piripa": "BA",
  "Piripiri": "PI",
  "Piritiba": "BA",
  "Pirpirituba": "PB",
  "Pitanga": "PR",
  "Pitangueiras": "SP",
  "Pitimbu": "PB",
  "Pium": "TO",
  "Piuma": "ES",
  "Placas": "PA",
  "Placido De Castro": "AC",
  "Planaltina Do Parana": "PR",
  "Planaltino": "BA",
  "Planalto": "PR",
  "Planalto Alegre": "SC",
  "Planalto Da Serra": "MT",
  "Platina": "SP",
  "Poa": "SP",
  "Pocao": "PE",
  "Pocinhos": "PB",
  "Poco Branco": "RN",
  "Poco Dantas": "PB",
  "Poco Das Antas": "RS",
  "Poco Das Trincheiras": "AL",
  "Poco De Jose De Moura": "PB",
  "Poco Redondo": "SE",
  "Poco Verde": "SE",
  "Pocoes": "BA",
  "Pocone": "MT",
  "Pojuca": "BA",
  "Poloni": "SP",
  "Pombal": "PB",
  "Pombos": "PE",
  "Pomerode": "SC",
  "Pompeia": "SP",
  "Pongai": "SP",
  "Ponta De Pedras": "PA",
  "Ponta Grossa": "PR",
  "Pontal": "SP",
  "Pontal Do Araguaia": "MT",
  "Pontal Do Parana": "PR",
  "Pontalinda": "SP",
  "Pontao": "RS",
  "Ponte Alta": "SC",
  "Ponte Alta Do Bom Jesus": "TO",
  "Ponte Alta Do Norte": "SC",
  "Ponte Alta Do Tocantins": "TO",
  "Ponte Branca": "MT",
  "Ponte Preta": "RS",
  "Ponte Serrada": "SC",
  "Pontes E Lacerda": "MT",
  "Pontes Gestal": "SP",
  "Ponto Belo": "ES",
  "Ponto Novo": "BA",
  "Populina": "SP",
  "Poranga": "CE",
  "Porangaba": "SP",
  "Porciuncula": "RJ",
  "Porecatu": "PR",
  "Portalegre": "RN",
  "Portao": "RS",
  "Porteiras": "CE",
  "Portel": "PA",
  "Porto": "PI",
  "Porto Acre": "AC",
  "Porto Alegre": "RS",
  "Porto Alegre Do Norte": "MT",
  "Porto Alegre Do Piaui": "PI",
  "Porto Alegre Do Tocantins": "TO",
  "Porto Amazonas": "PR",
  "Porto Barreiro": "PR",
  "Porto Belo": "SC",
  "Porto Calvo": "AL",
  "Porto Da Folha": "SE",
  "Porto De Moz": "PA",
  "Porto De Pedras": "AL",
  "Porto Do Mangue": "RN",
  "Porto Dos Gauchos": "MT",
  "Porto Esperidiao": "MT",
  "Porto Estrela": "MT",
  "Porto Feliz": "SP",
  "Porto Ferreira": "SP",
  "Porto Grande": "AP",
  "Porto Lucena": "RS",
  "Porto Maua": "RS",
  "Porto Nacional": "TO",
  "Porto Real": "RJ",
  "Porto Real Do Colegio": "AL",
  "Porto Rico": "PR",
  "Porto Seguro": "BA",
  "Porto Uniao": "SC",
  "Porto Vera Cruz": "RS",
  "Porto Vitoria": "PR",
  "Porto Walter": "AC",
  "Porto Xavier": "RS",
  "Potengi": "CE",
  "Potim": "SP",
  "Potiragua": "BA",
  "Potirendaba": "SP",
  "Potiretama": "CE",
  "Pouso Novo": "RS",
  "Pouso Redondo": "SC",
  "Poxoreo": "MT",
  "Pracinha": "SP",
  "Pracuuba": "AP",
  "Prado": "BA",
  "Prado Ferreira": "PR",
  "Pradopolis": "SP",
  "Praia Grande": "SC",
  "Praia Norte": "TO",
  "Prainha": "PA",
  "Pranchita": "PR",
  "Prata": "PB",
  "Prata Do Piaui": "PI",
  "Pratania": "SP",
  "Presidente Alves": "SP",
  "Presidente Bernardes": "SP",
  "Presidente Castelo Branco": "SC",
  "Presidente Dutra": "MA",
  "Presidente Epitacio": "SP",
  "Presidente Getulio": "SC",
  "Presidente Janio Quadros": "BA",
  "Presidente Juscelino": "RN",
  "Presidente Kennedy": "ES",
  "Presidente Lucena": "RS",
  "Presidente Nereu": "SC",
  "Presidente Prudente": "SP",
  "Presidente Tancredo Neves": "BA",
  "Presidente Venceslau": "SP",
  "Primavera": "PE",
  "Primavera Do Leste": "MT",
  "Primeiro De Maio": "PR",
  "Princesa": "SC",
  "Princesa Isabel": "PB",
  "Progresso": "RS",
  "Promissao": "SP",
  "Propria": "SE",
  "Protasio Alves": "RS",
  "Prudentopolis": "PR",
  "Pugmil": "TO",
  "Pureza": "RN",
  "Putinga": "RS",
  "Puxinana": "PB",
  "Quadra": "SP",
  "Quarai": "RS",
  "Quarto Centenario": "PR",
  "Quata": "SP",
  "Quatigua": "PR",
  "Quatipuru": "PA",
  "Quatis": "RJ",
  "Quatro Barras": "PR",
  "Quatro Irmaos": "RS",
  "Quatro Pontes": "PR",
  "Quebrangulo": "AL",
  "Quedas Do Iguacu": "PR",
  "Queimada Nova": "PI",
  "Queimadas": "BA",
  "Queimados": "RJ",
  "Queiroz": "SP",
  "Queluz": "SP",
  "Querencia": "MT",
  "Querencia Do Norte": "PR",
  "Quevedos": "RS",
  "Quijingue": "BA",
  "Quilombo": "SC",
  "Quinta Do Sol": "PR",
  "Quintana": "SP",
  "Quinze De Novembro": "RS",
  "Quipapa": "PE",
  "Quissama": "RJ",
  "Quitandinha": "PR",
  "Quiterianopolis": "CE",
  "Quixaba": "PE",
  "Quixabeira": "BA",
  "Quixada": "CE",
  "Quixelo": "CE",
  "Quixeramobim": "CE",
  "Quixere": "CE",
  "Rafael Fernandes": "RN",
  "Rafael Godeiro": "RN",
  "Rafael Jambeiro": "BA",
  "Rafard": "SP",
  "Ramilandia": "PR",
  "Rancharia": "SP",
  "Rancho Alegre": "PR",
  "Rancho Queimado": "SC",
  "Realeza": "PR",
  "Reboucas": "PR",
  "Recife": "PE",
  "Recursolandia": "TO",
  "Redencao": "CE",
  "Redencao Da Serra": "SP",
  "Redencao Do Gurgueia": "PI",
  "Redentora": "RS",
  "Regeneracao": "PI",
  "Regente Feijo": "SP",
  "Reginopolis": "SP",
  "Registro": "SP",
  "Relvado": "RS",
  "Remanso": "BA",
  "Remigio": "PB",
  "Renascenca": "PR",
  "Reriutaba": "CE",
  "Resende": "RJ",
  "Reserva": "PR",
  "Reserva Do Cabacal": "MT",
  "Reserva Do Iguacu": "PR",
  "Restinga": "SP",
  "Restinga Seca": "RS",
  "Retirolandia": "BA",
  "Riachao": "PB",
  "Riachao Das Neves": "BA",
  "Riachao Do Bacamarte": "PB",
  "Riachao Do Dantas": "SE",
  "Riachao Do Jacuipe": "BA",
  "Riachao Do Poco": "PB",
  "Riachinho": "TO",
  "Riacho Da Cruz": "RN",
  "Riacho Das Almas": "PE",
  "Riacho De Santana": "RN",
  "Riacho De Santo Antonio": "PB",
  "Riacho Dos Cavalos": "PB",
  "Riacho Frio": "PI",
  "Riachuelo": "RN",
  "Ribeira": "SP",
  "Ribeira Do Amparo": "BA",
  "Ribeira Do Piaui": "PI",
  "Ribeira Do Pombal": "BA",
  "Ribeirao": "PE",
  "Ribeirao Bonito": "SP",
  "Ribeirao Branco": "SP",
  "Ribeirao Cascalheira": "MT",
  "Ribeirao Claro": "PR",
  "Ribeirao Corrente": "SP",
  "Ribeirao Do Largo": "BA",
  "Ribeirao Do Pinhal": "PR",
  "Ribeirao Do Sul": "SP",
  "Ribeirao Dos Indios": "SP",
  "Ribeirao Grande": "SP",
  "Ribeirao Pires": "SP",
  "Ribeirao Preto": "SP",
  "Ribeiraozinho": "MT",
  "Ribeiro Goncalves": "PI",
  "Ribeiropolis": "SE",
  "Rifaina": "SP",
  "Rincao": "SP",
  "Rinopolis": "SP",
  "Rio Azul": "PR",
  "Rio Bananal": "ES",
  "Rio Bom": "PR",
  "Rio Bonito": "RJ",
  "Rio Bonito Do Iguacu": "PR",
  "Rio Branco": "MT",
  "Rio Branco Do Ivai": "PR",
  "Rio Branco Do Sul": "PR",
  "Rio Claro": "RJ",
  "Rio Da Conceicao": "TO",
  "Rio Das Antas": "SC",
  "Rio Das Flores": "RJ",
  "Rio Das Ostras": "RJ",
  "Rio Das Pedras": "SP",
  "Rio De Contas": "BA",
  "Rio De Janeiro": "RJ",
  "Rio Do Antonio": "BA",
  "Rio Do Campo": "SC",
  "Rio Do Fogo": "RN",
  "Rio Do Oeste": "SC",
  "Rio Do Pires": "BA",
  "Rio Do Sul": "SC",
  "Rio Dos Bois": "TO",
  "Rio Dos Cedros": "SC",
  "Rio Dos Indios": "RS",
  "Rio Formoso": "PE",
  "Rio Fortuna": "SC",
  "Rio Grande": "RS",
  "Rio Grande Da Serra": "SP",
  "Rio Grande Do Piaui": "PI",
  "Rio Largo": "AL",
  "Rio Maria": "PA",
  "Rio Negrinho": "SC",
  "Rio Negro": "PR",
  "Rio Novo Do Sul": "ES",
  "Rio Pardo": "RS",
  "Rio Real": "BA",
  "Rio Rufino": "SC",
  "Rio Sono": "TO",
  "Rio Tinto": "PB",
  "Riolandia": "SP",
  "Riozinho": "RS",
  "Riqueza": "SC",
  "Riversul": "SP",
  "Roca Sales": "RS",
  "Rodeio": "SC",
  "Rodeio Bonito": "RS",
  "Rodelas": "BA",
  "Rodolfo Fernandes": "RN",
  "Rodrigues Alves": "AC",
  "Rolador": "RS",
  "Rolandia": "PR",
  "Rolante": "RS",
  "Romelandia": "SC",
  "Roncador": "PR",
  "Ronda Alta": "RS",
  "Rondinha": "RS",
  "Rondolandia": "MT",
  "Rondon": "PR",
  "Rondon Do Para": "PA",
  "Rondonopolis": "MT",
  "Roque Gonzales": "RS",
  "Rorainopolis": "RR",
  "Rosana": "SP",
  "Rosario Do Catete": "SE",
  "Rosario Do Ivai": "PR",
  "Rosario Do Sul": "RS",
  "Rosario Oeste": "MT",
  "Roseira": "SP",
  "Roteiro": "AL",
  "Rubiacea": "SP",
  "Rubineia": "SP",
  "Ruropolis": "PA",
  "Russas": "CE",
  "Ruy Barbosa": "BA",
  "Sabaudia": "PR",
  "Sabino": "SP",
  "Saboeiro": "CE",
  "Sagrada Familia": "RS",
  "Sagres": "SP",
  "Saire": "PE",
  "Saldanha Marinho": "RS",
  "Sales": "SP",
  "Sales Oliveira": "SP",
  "Salesopolis": "SP",
  "Salete": "SC",
  "Salgadinho": "PE",
  "Salgado": "SE",
  "Salgado De Sao Felix": "PB",
  "Salgado Filho": "PR",
  "Salgueiro": "PE",
  "Salinas Da Margarida": "BA",
  "Salinopolis": "PA",
  "Salitre": "CE",
  "Salmourao": "SP",
  "Saloa": "PE",
  "Saltinho": "SC",
  "Salto": "SP",
  "Salto De Pirapora": "SP",
  "Salto Do Ceu": "MT",
  "Salto Do Itarare": "PR",
  "Salto Do Jacui": "RS",
  "Salto Do Lontra": "PR",
  "Salto Grande": "SP",
  "Salto Veloso": "SC",
  "Salvador": "BA",
  "Salvador Das Missoes": "RS",
  "Salvador Do Sul": "RS",
  "Salvaterra": "PA",
  "Sampaio": "TO",
  "Sananduva": "RS",
  "Sandolandia": "TO",
  "Sandovalina": "SP",
  "Sangao": "SC",
  "Sanharo": "PE",
  "Santa Adelia": "SP",
  "Santa Albertina": "SP",
  "Santa Amelia": "PR",
  "Santa Barbara": "BA",
  "Santa Barbara Do Para": "PA",
  "Santa Barbara Do Sul": "RS",
  "Santa Branca": "SP",
  "Santa Brigida": "BA",
  "Santa Carmem": "MT",
  "Santa Cecilia": "SC",
  "Santa Cecilia Do Pavao": "PR",
  "Santa Cecilia Do Sul": "RS",
  "Santa Clara Do Sul": "RS",
  "Santa Cruz": "PB",
  "Santa Cruz Cabralia": "BA",
  "Santa Cruz Da Baixa Verde": "PE",
  "Santa Cruz Da Conceicao": "SP",
  "Santa Cruz Da Esperanca": "SP",
  "Santa Cruz Da Vitoria": "BA",
  "Santa Cruz Das Palmeiras": "SP",
  "Santa Cruz De Monte Castelo": "PR",
  "Santa Cruz Do Arari": "PA",
  "Santa Cruz Do Capibaribe": "PE",
  "Santa Cruz Do Piaui": "PI",
  "Santa Cruz Do Rio Pardo": "SP",
  "Santa Cruz Do Sul": "RS",
  "Santa Cruz Do Xingu": "MT",
  "Santa Cruz Dos Milagres": "PI",
  "Santa Ernestina": "SP",
  "Santa Fe": "PR",
  "Santa Fe Do Araguaia": "TO",
  "Santa Fe Do Sul": "SP",
  "Santa Filomena": "PI",
  "Santa Gertrudes": "SP",
  "Santa Helena": "PB",
  "Santa Ines": "MA",
  "Santa Isabel": "SP",
  "Santa Isabel Do Ivai": "PR",
  "Santa Isabel Do Para": "PA",
  "Santa Izabel Do Oeste": "PR",
  "Santa Leopoldina": "ES",
  "Santa Lucia": "PR",
  "Santa Luz": "PI",
  "Santa Luzia": "BA",
  "Santa Luzia Do Itanhy": "SE",
  "Santa Luzia Do Norte": "AL",
  "Santa Luzia Do Para": "PA",
  "Santa Margarida Do Sul": "RS",
  "Santa Maria": "RN",
  "Santa Maria Da Boa Vista": "PE",
  "Santa Maria Da Serra": "SP",
  "Santa Maria Da Vitoria": "BA",
  "Santa Maria Das Barreiras": "PA",
  "Santa Maria De Jetiba": "ES",
  "Santa Maria Do Cambuca": "PE",
  "Santa Maria Do Herval": "RS",
  "Santa Maria Do Oeste": "PR",
  "Santa Maria Do Para": "PA",
  "Santa Maria Do Tocantins": "TO",
  "Santa Maria Madalena": "RJ",
  "Santa Mariana": "PR",
  "Santa Mercedes": "SP",
  "Santa Monica": "PR",
  "Santa Quiteria": "CE",
  "Santa Rita": "PB",
  "Santa Rita De Cassia": "BA",
  "Santa Rita Do Passa Quatro": "SP",
  "Santa Rita Do Tocantins": "TO",
  "Santa Rita Do Trivelato": "MT",
  "Santa Rosa": "RS",
  "Santa Rosa De Lima": "SC",
  "Santa Rosa De Viterbo": "SP",
  "Santa Rosa Do Piaui": "PI",
  "Santa Rosa Do Purus": "AC",
  "Santa Rosa Do Sul": "SC",
  "Santa Rosa Do Tocantins": "TO",
  "Santa Salete": "SP",
  "Santa Teresa": "ES",
  "Santa Teresinha": "BA",
  "Santa Tereza": "RS",
  "Santa Tereza Do Oeste": "PR",
  "Santa Tereza Do Tocantins": "TO",
  "Santa Terezinha": "MT",
  "Santa Terezinha De Itaipu": "PR",
  "Santa Terezinha Do Progresso": "SC",
  "Santa Terezinha Do Tocantins": "TO",
  "Santa Vitoria Do Palmar": "RS",
  "Santaluz": "BA",
  "Santana": "BA",
  "Santana Da Boa Vista": "RS",
  "Santana Da Ponte Pensa": "SP",
  "Santana De Mangueira": "PB",
  "Santana De Parnaiba": "SP",
  "Santana Do Acarau": "CE",
  "Santana Do Araguaia": "PA",
  "Santana Do Cariri": "CE",
  "Santana Do Ipanema": "AL",
  "Santana Do Itarare": "PR",
  "Santana Do Livramento": "RS",
  "Santana Do Matos": "RN",
  "Santana Do Mundau": "AL",
  "Santana Do Piaui": "PI",
  "Santana Do Sao Francisco": "SE",
  "Santana Do Serido": "RN",
  "Santana Dos Garrotes": "PB",
  "Santanopolis": "BA",
  "Santarem": "PB",
  "Santarem Novo": "PA",
  "Santiago": "RS",
  "Santiago Do Sul": "SC",
  "Santo Afonso": "MT",
  "Santo Amaro": "BA",
  "Santo Amaro Da Imperatriz": "SC",
  "Santo Amaro Das Brotas": "SE",
  "Santo Anastacio": "SP",
  "Santo Andre": "SP",
  "Santo Angelo": "RS",
  "Santo Antonio": "RN",
  "Santo Antonio Da Alegria": "SP",
  "Santo Antonio Da Patrulha": "RS",
  "Santo Antonio Da Platina": "PR",
  "Santo Antonio Das Missoes": "RS",
  "Santo Antonio De Jesus": "BA",
  "Santo Antonio De Lisboa": "PI",
  "Santo Antonio De Padua": "RJ",
  "Santo Antonio De Posse": "SP",
  "Santo Antonio Do Aracangua": "SP",
  "Santo Antonio Do Caiua": "PR",
  "Santo Antonio Do Jardim": "SP",
  "Santo Antonio Do Leste": "MT",
  "Santo Antonio Do Leverger": "MT",
  "Santo Antonio Do Palma": "RS",
  "Santo Antonio Do Paraiso": "PR",
  "Santo Antonio Do Pinhal": "SP",
  "Santo Antonio Do Planalto": "RS",
  "Santo Antonio Do Sudoeste": "PR",
  "Santo Antonio Do Taua": "PA",
  "Santo Antonio Dos Milagres": "PI",
  "Santo Augusto": "RS",
  "Santo Cristo": "RS",
  "Santo Estevao": "BA",
  "Santo Expedito": "SP",
  "Santo Expedito Do Sul": "RS",
  "Santo Inacio": "PR",
  "Santo Inacio Do Piaui": "PI",
  "Santopolis Do Aguapei": "SP",
  "Santos": "SP",
  "Sao Benedito": "CE",
  "Sao Benedito Do Sul": "PE",
  "Sao Bentinho": "PB",
  "Sao Bento": "PB",
  "Sao Bento Do Norte": "RN",
  "Sao Bento Do Sapucai": "SP",
  "Sao Bento Do Sul": "SC",
  "Sao Bento Do Tocantins": "TO",
  "Sao Bento Do Trairi": "RN",
  "Sao Bento Do Una": "PE",
  "Sao Bernardino": "SC",
  "Sao Bernardo Do Campo": "SP",
  "Sao Bonifacio": "SC",
  "Sao Borja": "RS",
  "Sao Bras": "AL",
  "Sao Braz Do Piaui": "PI",
  "Sao Caetano De Odivelas": "PA",
  "Sao Caetano Do Sul": "SP",
  "Sao Caitano": "PE",
  "Sao Carlos": "SP",
  "Sao Carlos Do Ivai": "PR",
  "Sao Cristovao": "SE",
  "Sao Cristovao Do Sul": "SC",
  "Sao Desiderio": "BA",
  "Sao Domingos": "SE",
  "Sao Domingos De Pombal": "PB",
  "Sao Domingos Do Araguaia": "PA",
  "Sao Domingos Do Capim": "PA",
  "Sao Domingos Do Cariri": "PB",
  "Sao Domingos Do Norte": "ES",
  "Sao Domingos Do Sul": "RS",
  "Sao Felipe": "BA",
  "Sao Felix": "BA",
  "Sao Felix Do Araguaia": "MT",
  "Sao Felix Do Piaui": "PI",
  "Sao Felix Do Tocantins": "TO",
  "Sao Felix Do Xingu": "PA",
  "Sao Fernando": "RN",
  "Sao Fidelis": "RJ",
  "Sao Francisco": "SP",
  "Sao Francisco De Assis": "RS",
  "Sao Francisco De Assis Do Piaui": "PI",
  "Sao Francisco De Itabapoana": "RJ",
  "Sao Francisco De Paula": "RS",
  "Sao Francisco Do Conde": "BA",
  "Sao Francisco Do Oeste": "RN",
  "Sao Francisco Do Para": "PA",
  "Sao Francisco Do Piaui": "PI",
  "Sao Francisco Do Sul": "SC",
  "Sao Gabriel": "RS",
  "Sao Gabriel Da Palha": "ES",
  "Sao Geraldo Do Araguaia": "PA",
  "Sao Goncalo": "RJ",
  "Sao Goncalo Do Amarante": "RN",
  "Sao Goncalo Do Gurgueia": "PI",
  "Sao Goncalo Do Piaui": "PI",
  "Sao Goncalo Dos Campos": "BA",
  "Sao Jeronimo": "RS",
  "Sao Jeronimo Da Serra": "PR",
  "Sao Joao": "PE",
  "Sao Joao Batista": "SC",
  "Sao Joao Da Baliza": "RR",
  "Sao Joao Da Barra": "RJ",
  "Sao Joao Da Boa Vista": "SP",
  "Sao Joao Da Canabrava": "PI",
  "Sao Joao Da Fronteira": "PI",
  "Sao Joao Da Ponta": "PA",
  "Sao Joao Da Serra": "PI",
  "Sao Joao Da Urtiga": "RS",
  "Sao Joao Da Varjota": "PI",
  "Sao Joao Das Duas Pontes": "SP",
  "Sao Joao De Iracema": "SP",
  "Sao Joao De Meriti": "RJ",
  "Sao Joao De Pirabas": "PA",
  "Sao Joao Do Araguaia": "PA",
  "Sao Joao Do Arraial": "PI",
  "Sao Joao Do Caiua": "PR",
  "Sao Joao Do Cariri": "PB",
  "Sao Joao Do Itaperiu": "SC",
  "Sao Joao Do Ivai": "PR",
  "Sao Joao Do Jaguaribe": "CE",
  "Sao Joao Do Oeste": "SC",
  "Sao Joao Do Piaui": "PI",
  "Sao Joao Do Polesine": "RS",
  "Sao Joao Do Rio Do Peixe": "PB",
  "Sao Joao Do Sabugi": "RN",
  "Sao Joao Do Sul": "SC",
  "Sao Joao Do Tigre": "PB",
  "Sao Joao Do Triunfo": "PR",
  "Sao Joaquim": "SC",
  "Sao Joaquim Da Barra": "SP",
  "Sao Joaquim Do Monte": "PE",
  "Sao Jorge": "RS",
  "Sao Jorge Do Ivai": "PR",
  "Sao Jorge Do Patrocinio": "PR",
  "Sao Jose": "SC",
  "Sao Jose Da Bela Vista": "SP",
  "Sao Jose Da Boa Vista": "PR",
  "Sao Jose Da Coroa Grande": "PE",
  "Sao Jose Da Lagoa Tapada": "PB",
  "Sao Jose Da Laje": "AL",
  "Sao Jose Da Tapera": "AL",
  "Sao Jose Da Vitoria": "BA",
  "Sao Jose Das Missoes": "RS",
  "Sao Jose Das Palmeiras": "PR",
  "Sao Jose De Caiana": "PB",
  "Sao Jose De Espinharas": "PB",
  "Sao Jose De Mipibu": "RN",
  "Sao Jose De Piranhas": "PB",
  "Sao Jose De Princesa": "PB",
  "Sao Jose De Uba": "RJ",
  "Sao Jose Do Barreiro": "SP",
  "Sao Jose Do Belmonte": "PE",
  "Sao Jose Do Bonfim": "PB",
  "Sao Jose Do Brejo Do Cruz": "PB",
  "Sao Jose Do Calcado": "ES",
  "Sao Jose Do Campestre": "RN",
  "Sao Jose Do Cedro": "SC",
  "Sao Jose Do Cerrito": "SC",
  "Sao Jose Do Divino": "PI",
  "Sao Jose Do Egito": "PE",
  "Sao Jose Do Herval": "RS",
  "Sao Jose Do Hortencio": "RS",
  "Sao Jose Do Inhacora": "RS",
  "Sao Jose Do Jacuipe": "BA",
  "Sao Jose Do Norte": "RS",
  "Sao Jose Do Ouro": "RS",
  "Sao Jose Do Peixe": "PI",
  "Sao Jose Do Piaui": "PI",
  "Sao Jose Do Povo": "MT",
  "Sao Jose Do Rio Claro": "MT",
  "Sao Jose Do Rio Pardo": "SP",
  "Sao Jose Do Rio Preto": "SP",
  "Sao Jose Do Sabugi": "PB",
  "Sao Jose Do Serido": "RN",
  "Sao Jose Do Vale Do Rio Preto": "RJ",
  "Sao Jose Do Xingu": "MT",
  "Sao Jose Dos Ausentes": "RS",
  "Sao Jose Dos Campos": "SP",
  "Sao Jose Dos Cordeiros": "PB",
  "Sao Jose Dos Pinhais": "PR",
  "Sao Jose Dos Quatro Marcos": "MT",
  "Sao Jose Dos Ramos": "PB",
  "Sao Juliao": "PI",
  "Sao Leopoldo": "RS",
  "Sao Lourenco Da Mata": "PE",
  "Sao Lourenco Da Serra": "SP",
  "Sao Lourenco Do Oeste": "SC",
  "Sao Lourenco Do Piaui": "PI",
  "Sao Lourenco Do Sul": "RS",
  "Sao Ludgero": "SC",
  "Sao Luis Do Curu": "CE",
  "Sao Luis Do Paraitinga": "SP",
  "Sao Luis Do Piaui": "PI",
  "Sao Luis Do Quitunde": "AL",
  "Sao Luiz": "RR",
  "Sao Luiz Gonzaga": "RS",
  "Sao Mamede": "PB",
  "Sao Manoel Do Parana": "PR",
  "Sao Manuel": "SP",
  "Sao Marcos": "RS",
  "Sao Martinho": "RS",
  "Sao Martinho Da Serra": "RS",
  "Sao Mateus": "ES",
  "Sao Mateus Do Sul": "PR",
  "Sao Miguel": "RN",
  "Sao Miguel Arcanjo": "SP",
  "Sao Miguel Da Baixa Grande": "PI",
  "Sao Miguel Da Boa Vista": "SC",
  "Sao Miguel Das Matas": "BA",
  "Sao Miguel Das Missoes": "RS",
  "Sao Miguel De Taipu": "PB",
  "Sao Miguel Do Aleixo": "SE",
  "Sao Miguel Do Fidalgo": "PI",
  "Sao Miguel Do Guama": "PA",
  "Sao Miguel Do Iguacu": "PR",
  "Sao Miguel Do Oeste": "SC",
  "Sao Miguel Do Tapuio": "PI",
  "Sao Miguel Do Tocantins": "TO",
  "Sao Miguel Dos Campos": "AL",
  "Sao Miguel Dos Milagres": "AL",
  "Sao Nicolau": "RS",
  "Sao Paulo": "SP",
  "Sao Paulo Das Missoes": "RS",
  "Sao Paulo Do Potengi": "RN",
  "Sao Pedro": "SP",
  "Sao Pedro Da Aldeia": "RJ",
  "Sao Pedro Da Cipa": "MT",
  "Sao Pedro Da Serra": "RS",
  "Sao Pedro De Alcantara": "SC",
  "Sao Pedro Do Butia": "RS",
  "Sao Pedro Do Iguacu": "PR",
  "Sao Pedro Do Ivai": "PR",
  "Sao Pedro Do Parana": "PR",
  "Sao Pedro Do Piaui": "PI",
  "Sao Pedro Do Sul": "RS",
  "Sao Pedro Do Turvo": "SP",
  "Sao Rafael": "RN",
  "Sao Raimundo Nonato": "PI",
  "Sao Roque": "SP",
  "Sao Roque Do Canaa": "ES",
  "Sao Salvador Do Tocantins": "TO",
  "Sao Sebastiao": "AL",
  "Sao Sebastiao Da Amoreira": "PR",
  "Sao Sebastiao Da Boa Vista": "PA",
  "Sao Sebastiao Da Grama": "SP",
  "Sao Sebastiao De Lagoa De Roca": "PB",
  "Sao Sebastiao Do Alto": "RJ",
  "Sao Sebastiao Do Cai": "RS",
  "Sao Sebastiao Do Passe": "BA",
  "Sao Sebastiao Do Tocantins": "TO",
  "Sao Sebastiao Do Umbuzeiro": "PB",
  "Sao Sepe": "RS",
  "Sao Simao": "SP",
  "Sao Tome": "RN",
  "Sao Valentim": "RS",
  "Sao Valentim Do Sul": "RS",
  "Sao Valerio Da Natividade": "TO",
  "Sao Valerio Do Sul": "RS",
  "Sao Vendelino": "RS",
  "Sao Vicente": "RN",
  "Sao Vicente Do Sul": "RS",
  "Sao Vicente Ferrer": "PE",
  "Sape": "PB",
  "Sapeacu": "BA",
  "Sapezal": "MT",
  "Sapiranga": "RS",
  "Sapopema": "PR",
  "Sapucaia": "PA",
  "Sapucaia Do Sul": "RS",
  "Saquarema": "RJ",
  "Sarandi": "PR",
  "Sarapui": "SP",
  "Sarutaia": "SP",
  "Satiro Dias": "BA",
  "Satuba": "AL",
  "Saubara": "BA",
  "Saudade Do Iguacu": "PR",
  "Saudades": "SC",
  "Saude": "BA",
  "Schroeder": "SC",
  "Seabra": "BA",
  "Seara": "SC",
  "Sebastianopolis Do Sul": "SP",
  "Sebastiao Barros": "PI",
  "Sebastiao Laranjeiras": "BA",
  "Sebastiao Leal": "PI",
  "Seberi": "RS",
  "Sede Nova": "RS",
  "Segredo": "RS",
  "Selbach": "RS",
  "Sena Madureira": "AC",
  "Senador Eloi De Souza": "RN",
  "Senador Georgino Avelino": "RN",
  "Senador Guiomard": "AC",
  "Senador Jose Porfirio": "PA",
  "Senador Pompeu": "CE",
  "Senador Rui Palmeira": "AL",
  "Senador Sa": "CE",
  "Senador Salgado Filho": "RS",
  "Senges": "PR",
  "Senhor Do Bonfim": "BA",
  "Sentinela Do Sul": "RS",
  "Sento Se": "BA",
  "Serafina Correa": "RS",
  "Serido": "PB",
  "Serio": "RS",
  "Seropedica": "RJ",
  "Serra": "ES",
  "Serra Alta": "SC",
  "Serra Azul": "SP",
  "Serra Branca": "PB",
  "Serra Da Raiz": "PB",
  "Serra De Sao Bento": "RN",
  "Serra Do Mel": "RN",
  "Serra Do Navio": "AP",
  "Serra Do Ramalho": "BA",
  "Serra Dourada": "BA",
  "Serra Grande": "PB",
  "Serra Negra": "SP",
  "Serra Negra Do Norte": "RN",
  "Serra Nova Dourada": "MT",
  "Serra Preta": "BA",
  "Serra Redonda": "PB",
  "Serra Talhada": "PE",
  "Serrana": "SP",
  "Serranopolis Do Iguacu": "PR",
  "Serraria": "PB",
  "Serrinha": "BA",
  "Serrinha Dos Pintos": "RN",
  "Serrita": "PE",
  "Serrolandia": "BA",
  "Sertaneja": "PR",
  "Sertania": "PE",
  "Sertanopolis": "PR",
  "Sertao": "RS",
  "Sertao Santana": "RS",
  "Sertaozinho": "SP",
  "Sete Barras": "SP",
  "Sete De Setembro": "RS",
  "Severiano De Almeida": "RS",
  "Severiano Melo": "RN",
  "Severinia": "SP",
  "Sideropolis": "SC",
  "Sigefredo Pacheco": "PI",
  "Silva Jardim": "RJ",
  "Silvanopolis": "TO",
  "Silveira Martins": "RS",
  "Silveiras": "SP",
  "Simao Dias": "SE",
  "Simoes": "PI",
  "Simoes Filho": "BA",
  "Simplicio Mendes": "PI",
  "Sinimbu": "RS",
  "Sinop": "MT",
  "Siqueira Campos": "PR",
  "Sirinhaem": "PE",
  "Siriri": "SE",
  "Sitio Do Mato": "BA",
  "Sitio Do Quinto": "BA",
  "Sitio Novo": "RN",
  "Sitio Novo Do Tocantins": "TO",
  "Sobradinho": "BA",
  "Sobrado": "PB",
  "Sobral": "CE",
  "Socorro": "SP",
  "Socorro Do Piaui": "PI",
  "Solanea": "PB",
  "Soledade": "RS",
  "Solidao": "PE",
  "Solonopole": "CE",
  "Sombrio": "SC",
  "Sooretama": "ES",
  "Sorocaba": "SP",
  "Sorriso": "MT",
  "Sossego": "PB",
  "Soure": "PA",
  "Sousa": "PB",
  "Souto Soares": "BA",
  "Sucupira": "TO",
  "Sud Mennucci": "SP",
  "Sul Brasil": "SC",
  "Sulina": "PR",
  "Sumare": "SP",
  "Sume": "PB",
  "Sumidouro": "RJ",
  "Surubim": "PE",
  "Sussuapara": "PI",
  "Suzanapolis": "SP",
  "Suzano": "SP",
  "São Felix Do Coribe": "BA",
  "São Miguel Do Gostoso": "RN",
  "Tabai": "RS",
  "Tabapora": "MT",
  "Tabapua": "SP",
  "Tabatinga": "SP",
  "Tabira": "PE",
  "Taboao Da Serra": "SP",
  "Tabocas Do Brejo Velho": "BA",
  "Taboleiro Grande": "RN",
  "Tabuleiro Do Norte": "CE",
  "Tacaimbo": "PE",
  "Tacaratu": "PE",
  "Taciba": "SP",
  "Taguai": "SP",
  "Taguatinga": "TO",
  "Taiacu": "SP",
  "Tailandia": "PA",
  "Taio": "SC",
  "Taipas Do Tocantins": "TO",
  "Taipu": "RN",
  "Taiuva": "SP",
  "Talisma": "TO",
  "Tamandare": "PE",
  "Tamarana": "PR",
  "Tambau": "SP",
  "Tamboara": "PR",
  "Tamboril": "CE",
  "Tamboril Do Piaui": "PI",
  "Tanabi": "SP",
  "Tangara": "SC",
  "Tangara Da Serra": "MT",
  "Tangua": "RJ",
  "Tanhacu": "BA",
  "Tanque Do Piaui": "PI",
  "Tanque Novo": "BA",
  "Tanquinho": "BA",
  "Tapejara": "PR",
  "Tapera": "RS",
  "Taperoa": "BA",
  "Tapes": "RS",
  "Tapira": "PR",
  "Tapirai": "SP",
  "Tapiramuta": "BA",
  "Tapiratiba": "SP",
  "Tapurah": "MT",
  "Taquara": "RS",
  "Taquaral": "SP",
  "Taquarana": "AL",
  "Taquari": "RS",
  "Taquaritinga": "SP",
  "Taquaritinga Do Norte": "PE",
  "Taquarituba": "SP",
  "Taquarivai": "SP",
  "Taquarucu Do Sul": "RS",
  "Tarabai": "SP",
  "Tarauaca": "AC",
  "Tarrafas": "CE",
  "Tartarugalzinho": "AP",
  "Taruma": "SP",
  "Tatui": "SP",
  "Taua": "CE",
  "Taubate": "SP",
  "Tavares": "RS",
  "Teixeira": "PB",
  "Teixeira De Freitas": "BA",
  "Teixeira Soares": "PR",
  "Tejucuoca": "CE",
  "Tejupa": "SP",
  "Telemaco Borba": "PR",
  "Telha": "SE",
  "Tenente Ananias": "RN",
  "Tenente Laurentino Cruz": "RN",
  "Tenente Portela": "RS",
  "Tenorio": "PB",
  "Teodoro Sampaio": "BA",
  "Teofilandia": "BA",
  "Teolandia": "BA",
  "Teotonio Vilela": "AL",
  "Teresina": "PI",
  "Teresopolis": "RJ",
  "Terezinha": "PE",
  "Terra Alta": "PA",
  "Terra Boa": "PR",
  "Terra De Areia": "RS",
  "Terra Nova": "BA",
  "Terra Nova Do Norte": "MT",
  "Terra Rica": "PR",
  "Terra Roxa": "PR",
  "Terra Santa": "PA",
  "Tesouro": "MT",
  "Teutonia": "RS",
  "Tiangua": "CE",
  "Tibagi": "PR",
  "Tibau": "RN",
  "Tibau Do Sul": "RN",
  "Tiete": "SP",
  "Tigrinhos": "SC",
  "Tijucas": "SC",
  "Tijucas Do Sul": "PR",
  "Timbauba": "PE",
  "Timbauba Dos Batistas": "RN",
  "Timbe Do Sul": "SC",
  "Timbo": "SC",
  "Timbo Grande": "SC",
  "Timburi": "SP",
  "Tio Hugo": "RS",
  "Tiradentes Do Sul": "RS",
  "Tobias Barreto": "SE",
  "Tocantinia": "TO",
  "Tocantinopolis": "TO",
  "Toledo": "PR",
  "Tomar Do Geru": "SE",
  "Tomazina": "PR",
  "Tome-Acu": "PA",
  "Toritama": "PE",
  "Torixoreu": "MT",
  "Toropi": "RS",
  "Torre De Pedra": "SP",
  "Torres": "RS",
  "Torrinha": "SP",
  "Touros": "RN",
  "Trabiju": "SP",
  "Tracuateua": "PA",
  "Tracunhaem": "PE",
  "Traipu": "AL",
  "Trairao": "PA",
  "Trairi": "CE",
  "Trajano De Morais": "RJ",
  "Tramandai": "RS",
  "Travesseiro": "RS",
  "Tremedal": "BA",
  "Tremembe": "SP",
  "Tres Arroios": "RS",
  "Tres Barras": "SC",
  "Tres Barras Do Parana": "PR",
  "Tres Cachoeiras": "RS",
  "Tres Coroas": "RS",
  "Tres De Maio": "RS",
  "Tres Forquilhas": "RS",
  "Tres Fronteiras": "SP",
  "Tres Palmeiras": "RS",
  "Tres Passos": "RS",
  "Tres Rios": "RJ",
  "Treviso": "SC",
  "Treze De Maio": "SC",
  "Treze Tilias": "SC",
  "Trindade": "PE",
  "Trindade Do Sul": "RS",
  "Triunfo": "PE",
  "Triunfo Potiguar": "RN",
  "Trombudo Central": "SC",
  "Tubarao": "SC",
  "Tucano": "BA",
  "Tucuma": "PA",
  "Tucunduva": "RS",
  "Tucurui": "PA",
  "Tuiuti": "SP",
  "Tunapolis": "SC",
  "Tunas": "RS",
  "Tunas Do Parana": "PR",
  "Tuneiras Do Oeste": "PR",
  "Tupa": "SP",
  "Tupanatinga": "PE",
  "Tupanci Do Sul": "RS",
  "Tupancireta": "RS",
  "Tupandi": "RS",
  "Tuparendi": "RS",
  "Tuparetama": "PE",
  "Tupassi": "PR",
  "Tupi Paulista": "SP",
  "Tupirama": "TO",
  "Tupiratins": "TO",
  "Turiuba": "SP",
  "Turmalina": "SP",
  "Turucu": "RS",
  "Tururu": "CE",
  "Turvo": "PR",
  "Uaua": "BA",
  "Ubaira": "BA",
  "Ubaitaba": "BA",
  "Ubajara": "CE",
  "Ubarana": "SP",
  "Ubata": "BA",
  "Ubatuba": "SP",
  "Ubirajara": "SP",
  "Ubirata": "PR",
  "Ubiretama": "RS",
  "Uchoa": "SP",
  "Uibai": "BA",
  "Uiramuta": "RR",
  "Uirauna": "PB",
  "Ulianopolis": "PA",
  "Umari": "CE",
  "Umarizal": "RN",
  "Umbauba": "SE",
  "Umburanas": "BA",
  "Umbuzeiro": "PB",
  "Umirim": "CE",
  "Umuarama": "PR",
  "Una": "BA",
  "Uniao": "PI",
  "Uniao Da Serra": "RS",
  "Uniao Da Vitoria": "PR",
  "Uniao Do Oeste": "SC",
  "Uniao Do Sul": "MT",
  "Uniao Dos Palmares": "AL",
  "Uniao Paulista": "SP",
  "Uniflor": "PR",
  "Unistalda": "RS",
  "Upanema": "RN",
  "Urai": "PR",
  "Urandi": "BA",
  "Urania": "SP",
  "Uru": "SP",
  "Uruara": "PA",
  "Urubici": "SC",
  "Uruburetama": "CE",
  "Urucuca": "BA",
  "Urucui": "PI",
  "Uruguaiana": "RS",
  "Uruoca": "CE",
  "Urupema": "SC",
  "Urupes": "SP",
  "Urussanga": "SC",
  "Utinga": "BA",
  "Vacaria": "RS",
  "Vale De São Domingos": "MT",
  "Vale Do Sol": "RS",
  "Vale Real": "RS",
  "Vale Verde": "RS",
  "Valenca": "RJ",
  "Valenca Do Piaui": "PI",
  "Valente": "BA",
  "Valentim Gentil": "SP",
  "Valinhos": "SP",
  "Valparaiso": "SP",
  "Vanini": "RS",
  "Vargeao": "SC",
  "Vargem": "SP",
  "Vargem Alta": "ES",
  "Vargem Bonita": "SC",
  "Vargem Grande Do Sul": "SP",
  "Vargem Grande Paulista": "SP",
  "Varjota": "CE",
  "Varre-Sai": "RJ",
  "Varzea": "PB",
  "Varzea Alegre": "CE",
  "Varzea Branca": "PI",
  "Varzea Da Roca": "BA",
  "Varzea Do Poco": "BA",
  "Varzea Grande": "PI",
  "Varzea Nova": "BA",
  "Varzea Paulista": "SP",
  "Varzedo": "BA",
  "Vassouras": "RJ",
  "Venancio Aires": "RS",
  "Venda Nova Do Imigrante": "ES",
  "Venha-Ver": "RN",
  "Ventania": "PR",
  "Venturosa": "PE",
  "Vera": "MT",
  "Vera Cruz": "RN",
  "Vera Cruz Do Oeste": "PR",
  "Vera Mendes": "PI",
  "Veranopolis": "RS",
  "Verdejante": "PE",
  "Vere": "PR",
  "Vereda": "BA",
  "Vertente Do Lerio": "PE",
  "Vertentes": "PE",
  "Vespasiano Correa": "RS",
  "Viadutos": "RS",
  "Viamao": "RS",
  "Viana": "ES",
  "Vicencia": "PE",
  "Vicente Dutra": "RS",
  "Vicosa": "RN",
  "Vicosa Do Ceara": "CE",
  "Victor Graeff": "RS",
  "Vidal Ramos": "SC",
  "Videira": "SC",
  "Vieiropolis": "PB",
  "Vigia": "PA",
  "Vila Bela Da Santissima Trindade": "MT",
  "Vila Flor": "RN",
  "Vila Flores": "RS",
  "Vila Langaro": "RS",
  "Vila Maria": "RS",
  "Vila Nova Do Piaui": "PI",
  "Vila Nova Do Sul": "RS",
  "Vila Pavao": "ES",
  "Vila Rica": "MT",
  "Vila Valerio": "ES",
  "Vila Velha": "ES",
  "Vinhedo": "SP",
  "Viradouro": "SP",
  "Virmond": "PR",
  "Viseu": "PA",
  "Vista Alegre": "RS",
  "Vista Alegre Do Alto": "SP",
  "Vista Alegre Do Prata": "RS",
  "Vista Gaucha": "RS",
  "Vista Serrana": "PB",
  "Vitor Meireles": "SC",
  "Vitoria": "ES",
  "Vitoria Brasil": "SP",
  "Vitoria Da Conquista": "BA",
  "Vitoria Das Missoes": "RS",
  "Vitoria De Santo Antao": "PE",
  "Vitoria Do Jari": "AP",
  "Vitoria Do Xingu": "PA",
  "Vitorino": "PR",
  "Volta Redonda": "RJ",
  "Votorantim": "SP",
  "Votuporanga": "SP",
  "Wagner": "BA",
  "Wall Ferraz": "PI",
  "Wanderlandia": "TO",
  "Wanderley": "BA",
  "Wenceslau Braz": "PR",
  "Wenceslau Guimaraes": "BA",
  "Westfalia": "RS",
  "Witmarsum": "SC",
  "Xambioa": "TO",
  "Xambre": "PR",
  "Xangri-La": "RS",
  "Xanxere": "SC",
  "Xapuri": "AC",
  "Xavantina": "SC",
  "Xaxim": "SC",
  "Xexeu": "PE",
  "Xinguara": "PA",
  "Xique-Xique": "BA",
  "Zabele": "PB",
  "Zacarias": "SP",
  "Zortea": "SC",
"Santa Inês": "MA",
"Pio XII": "MA",
"Vitorino Freire": "MA",
"Esperantinopolis": "MA",
"Joselandia": "MA",
"Senador Alexandre Costa": "MA",
"Bau": "MA",
"União": "PI",
"Coelho Neto": "MA",
"Afonso Cunha": "MA",
"Chapadinha": "MA",
"Caxias": "MA",
"Codo": "MA",
"Peritoro": "MA",
"Miranda do Norte": "MA",
"São Luis": "MA",
"Rosario": "MA",
"Sobradinho": "MA",
"Zé Doca": "MA",
"Bacabal": "MA",
"Buriticupu": "MA",
"Vitoria do Mearim": "MA",
"Urbano Santos": "MA",
"Globnet": "CE",
"Ascenty": "CE",
"Bacabeira": "MA",
"Barra do Corda": "MA",
"Colinas": "MA",
"Grajau": "MA",
"Imperatriz": "MA",
"Itaipava do Grajau": "MA",
"Paraibano": "MA",
"Alto Alegre do Maranhão": "MA",
  "Bom Jesus das Selvas": "MA",
  "Riachão": "MA",
  "Bom Sucesso": "MA",
  "Central do Maranhão": "MA",
  "Pinheiro": "MA",
  "Bom Jardim": "MA",
  "São Domingos do Maranhão": "MA",
  "Morros": "MA",
  "Massalina": "MA",
  "Itapecuru-Mirim": "MA",
  "Pedro Rosario": "MA",
  "Santa Luzia do Paruá": "MA",
};
